const { GLOBAL_COLOR } = require("./constants");

module.exports = {
  siteName: "Meyhomes",
  copyright: "",
  logoPath: require("../images/logo_waterpoint@1x.png"),
  logoPath2: require("../images/logo_waterpoint_lg_white.png"),
  logoPath3: require("../images/logo_waterpoint_lg.png"),
  logoPath4: require("../images/logo_tadt.jpg"),
  apiPrefix: "/api/v1",
  fixedHeader: true, // sticky primary layout header
  projectName: {
    name: "TSQ Euroland",
    address: "Số 7 Nguyễn Văn Lộc - Mỗ Lao - Hà Đông - Hà Nội",
    phonenumber: "0988 888888",
  },
  MAX_LEVEL_CLUSTER_SHOW: 2,
  NAME_CLUSTER: ["cụm", "Cấp 1", "Cấp 2", "Cấp 3"],
  COLOR_LIST: [
    "#FF6900",
    "#FCB900",
    "#7BDCB5",
    "#00D084",
    "#8ED1FC",
    "#0693E3",
    "#ABB8C3",
    "#EB144C",
    "#F78DA7",
    "#9900EF",
  ],
  COLOR_CHART: [
    GLOBAL_COLOR,
    "#ff6600",
    "#ffb84d",
    "#51a6fb",
    "#339966",
    "#546E7A",
    "#FF9800",
    "#009999",
    "#EB144C",
    "#F78DA7",
    "#9900EF",
  ],
  UNIT_SERVICE_CONFIG: [
    { value: 0, title: "m2", title_en: "m2" },
    { value: 1, title: "Bất động sản", title_en: "Property" },
  ],
  MONTH_CYCLE_SERVICE_CONFIG: [
    { value: 1, title: "Hàng tháng", title_en: "monthly" },
    { value: 3, title: "3 tháng", title_en: "3 months" },
    { value: 6, title: "6 tháng", title_en: "6 months" },
    { value: 12, title: "12 tháng", title_en: "12 months" },
  ],

  ICON_SERVICE: [
    //'icWater', 'icPower', 'icCarParking', 'icRideParking', 'icInternet'
    {
      name: "Nước",
      value: "icWater",
      icon: require("../images/icWater.png"),
    },
    {
      name: "Điện",
      value: "icPower",
      icon: require("../images/icPower.png"),
    },
    {
      name: "Gửi ôtô",
      value: "icCarParking",
      icon: require("../images/icCarParking.png"),
    },
    {
      name: "Gửi xe máy",
      value: "icRideParking",
      icon: require("../images/icRideParking.png"),
    },
    {
      name: "Mạng",
      value: "icInternet",
      icon: require("../images/icInternet.png"),
    },
  ],
  TYPE_RESIDENT: [
    {
      id: 0,
      name: "Gia đình chủ hộ",
      name_en: "Householder's family",
    },
    {
      id: 1,
      name: "Chủ hộ",
      name_en: "Householder",
    },
    {
      id: 2,
      name: "Khách thuê",
      name_en: "Renter",
    },
    {
      id: 3,
      name: "Gia đình khách thuê",
      name_en: "Renter's family",
    },
  ],
  TYPE_PAYMENT: [
    {
      id: 0,
      name: "Tiền mặt",
      name_en: "Cash",
    },
    {
      id: 1,
      name: "Chuyển khoản",
      name_en: "Transfer",
    },
    {
      id: 2,
      name: "Thanh toán ngân lượng",
      name_en: "Cash payment",
    },
    {
      id: 3,
      name: "Cà thẻ",
      name_en: "Card payment",
    },
    // {
    //   id: 4,
    //   name: "Ví MoMo",
    //   name_en: "MoMo wallet",
    // },
    {
      id: 4,
      name: "Ví VNPay",
      name_en: "VNPay wallet",
    },
  ],
  STATUS_APARTMENT: [
    {
      id: 0,
      name: "Chưa ở",
      name_en: "Vacant",
    },
    {
      id: 1,
      name: "Đã ở",
      name_en: "Occupied",
    },
  ],
  STATUS_HANDOVER: [
    {
      id: 0,
      name: "Chưa bàn giao",
      name_en: "Not handover",
    },
    {
      id: 1,
      name: "Đã bàn giao",
      name_en: "Handover",
    },
  ],
  STATUS_REQUEST: [
    {
      id: -2,
      name: "Đã hủy",
      name_en: "Canceled",
      color: "#D8CBCB",
    },
    {
      id: -1,
      name: "Chờ xử lý",
      name_en: "Pending",
      color: "#ffc340",
    },
    {
      id: 0,
      name: "Mới",
      name_en: "New",
      color: "#f5f5f5",
    },
    {
      id: 1,
      name: "Đang xử lý",
      name_en: "In progress",
      color: "#006400",
    },
    {
      id: 2,
      name: "Đã xử lý",
      name_en: "Resolved",
      color: "#00D084",
    },
    // {
    //   id: 3,
    //   name: "Mở lại",
    //   name_en: "Reopen",
    //   color: "#ff0000",
    // },
    {
      id: 4,
      name: "Đã đóng",
      name_en: "Closed",
      color: "#696969",
    },
  ],
  STATUS_NOTIFICATION: [
    {
      id: 0,
      name: "Nháp",
      name_en: "Draft",
      className: "luci-status-warning",
    },
    {
      id: 1,
      name: "Công khai",
      name_en: "Public",
      className: "luci-status-success",
    },
    {
      id: 2,
      name: "Hẹn giờ",
      name_en: "Timer",
      className: "luci-status-danger",
    },
  ],
  STATUS_SERVICE_PROVIDER: [
    {
      id: 0,
      name: "Ngừng cung cấp",
      name_en: "Ceased operations",
    },
    {
      id: 1,
      name: "Đang cung cấp",
      name_en: "In operations",
    },
  ],
  TYPE_GROUP_USER: [
    {
      id: 0,
      name: "Ban quản lý",
    },
    {
      id: 1,
      name: "Ban quản trị",
    },
  ],

  STATUS_SERVICE_PAYMENT: [
    {
      id: 0,
      name: "Chưa thanh toán",
      name_en: "Unpaid",
    },
    {
      id: 1,
      name: "Đã thanh toán",
      name_en: "Paid",
    },
  ],

  STATUS_TYPE: [
    {
      id: "1",
      label: "Đang hoạt động",
      label_en: "Active",
    },
    {
      id: "0",
      label: "Tạm ngừng hoạt động",
      label_en: "Operation suspended",
    },
    {
      id: "-1",
      label: "Dừng hoạt động",
      label_en: "Inactive",
    },
  ],

  BOOKING_TYPE: [
    {
      id: "0",
      label: "Đặt theo lượt",
      label_en: "Booking by turn",
    },
    {
      id: "1",
      label: "Đặt theo chỗ",
      label_en: "Booking by slot",
    },
    {
      id: "2",
      label: "Đặt theo thời gian",
      label_en: "Booking by time",
    },
  ],
  APARTMENT_TYPE: [
    {
      id: "0",
      label: "Căn hộ chung cư",
    },
    {
      id: "1",
      label: "Shop house",
    },
    {
      id: "2",
      label: "Pent house",
    },
    {
      id: "3",
      label: "Office tel",
    },
  ],
  //TODO: Sua cau hinh template Notification
  NOTIFICATION_TYPE: [
    {
      id: "0",
      label: "Thông báo thường",
      label_en: "Normal announcement",
    },
    {
      id: "5",
      label: "Thông báo phí",
      label_en: "Fee announcement",
    },
    {
      id: "6",
      label: "Thông báo khảo sát",
      label_en: "Survey announcement",
    },
    {
      id: "1",
      label: "Nhắc nợ lần 1",
      label_en: "1st payment reminder",
    },
    {
      id: "2",
      label: "Nhắc nợ lần 2",
      label_en: "2nd payment reminder",
    },
    {
      id: "3",
      label: "Nhắc nợ lần 3",
      label_en: "3rd payment reminder",
    },
    {
      id: "4",
      label: "Tạm ngừng dịch vụ",
      label_en: "Stop service",
    },
  ],

  NOTIFICATION_FEE_TYPE: [
    // {
    //   id: "0",
    //   label: "Thông báo thường",
    //   label_en: "Normal announcement",
    // },
    {
      id: "1",
      label: "Thông báo phí",
      label_en: "Fee notification",
    },
    // {
    //   id: "6",
    //   label: "Thông báo khảo sát",
    //   label_en: "Survey announcement",
    // },
    {
      id: "2",
      label: "Nhắc nợ lần 1",
      label_en: "1st payment reminder",
    },
    {
      id: "3",
      label: "Nhắc nợ lần 2",
      label_en: "2nd payment reminder",
    },
    {
      id: "4",
      label: "Nhắc nợ lần 3",
      label_en: "3rd payment reminder",
    },
    {
      id: "5",
      label: "Tạm ngừng dịch vụ",
      label_en: "Stop service",
    },
  ],

  /* Layout configuration, specify which layout to use for route. */
  layouts: [
    {
      name: "primary",
      include: [/.*/],
      exclude: [/(\/(en|zh))*\/login/],
    },
  ],
  RELATIONSHIP_APARTMENT: [
    {
      id: 0,
      title: "Chủ hộ",
      title_en: "Householder",
    },
    {
      id: 1,
      title: "Ông/Bà",
      title_en: "Grandparents",
    },
    {
      id: 2,
      title: "Bố/Mẹ",
      title_en: "Parent",
    },
    {
      id: 3,
      title: "Vợ/Chồng",
      title_en: "Spouse",
    },
    {
      id: 4,
      title: "Con",
      title_en: "Child",
    },
    {
      id: 5,
      title: "Anh/Chị/Em",
      title_en: "Sibling",
    },
    {
      id: 6,
      title: "Bạn",
      title_en: "Friend",
    },
    {
      id: 7,
      title: "Khác",
      title_en: "Other",
    },
  ],
  NOTIFY_TYPE: [
    {
      type: 0,
      type_name: "Thông báo thường",
    },
    {
      type: 1,
      type_name: "Thông báo sự kiện",
    },
    {
      type: 2,
      type_name: "Thông báo tài chính/công nợ",
    },
    {
      type: 3,
      type_name: "Thông báo yêu cầu/phản ánh",
    },
    {
      type: 4,
      type_name: "Thông báo đặt dịch vụ",
    },
    {
      type: 5,
      type_name: "Thông báo công việc",
    },
  ],
  INSTALL_APP: [
    {
      id: 0,
      name: "Chưa cài",
      name_en: "Not installed",
    },
    {
      id: 1,
      name: "Đã cài",
      name_en: "Install app",
    },
  ],
  MAINTAIN_DEVICES: [
    {
      id: 0,
      name: "Máy tính",
      name_en: "Computer",
    },
    {
      id: 1,
      name: "Quạt",
      name_en: "Fan",
    },
    {
      id: 2,
      name: "Camera",
      name_en: "Camera",
    },
    {
      id: 3,
      name: "Đèn",
      name_en: "Lamp",
    },
    {
      id: 4,
      name: "Thang máy",
      name_en: "Elevator",
    },
  ],
  MAINTAIN_DEVICES_TERM: [
    {
      id: 0,
      name: "Không lặp lại",
      name_en: "No repeat",
    },
    {
      id: 1,
      name: "1 tháng",
      name_en: "1 month",
    },
    {
      id: 2,
      name: "2 tháng",
      name_en: "2 months",
    },
    {
      id: 3,
      name: "3 tháng",
      name_en: "3 months",
    },
    {
      id: 4,
      name: "6 tháng",
      name_en: "6 months",
    },
    {
      id: 5,
      name: "12 tháng",
      name_en: "12 months",
    },
    {
      id: 6,
      name: "24 tháng",
      name_en: "24 months",
    },
  ],
  CUSTOM_TOOLBAR: {
    options: [
      "inline",
      "blockType",
      "fontSize",
      "fontFamily",
      "list",
      "textAlign",
      "colorPicker",
      "link",
      "image",
      "history",
    ],
    inline: {
      options: ["bold", "italic", "underline", "strikethrough", "monospace"],
    },
  },
  editorLabelsVN: {
    // Generic
    "generic.add": "Thêm",
    "generic.cancel": "Hủy",

    // BlockType
    "components.controls.blocktype.h1": "Heading 1",
    "components.controls.blocktype.h2": "Heading 2",
    "components.controls.blocktype.h3": "Heading 3",
    "components.controls.blocktype.h4": "Heading 4",
    "components.controls.blocktype.h5": "Heading 5",
    "components.controls.blocktype.h6": "Heading 6",
    "components.controls.blocktype.blockquote": "Blockquote",
    "components.controls.blocktype.code": "Code",
    "components.controls.blocktype.blocktype": "Kiểu khối",
    "components.controls.blocktype.normal": "Normal",

    // Color Picker
    "components.controls.colorpicker.colorpicker": "Chọn màu",
    "components.controls.colorpicker.text": "Chữ",
    "components.controls.colorpicker.background": "Nền",

    // Embedded
    "components.controls.embedded.embedded": "Nhúng",
    "components.controls.embedded.embeddedlink": "Nhúng liên kết",
    "components.controls.embedded.enterlink": "Nhập liên kết",

    // Emoji
    "components.controls.emoji.emoji": "Emoji",

    // FontFamily
    "components.controls.fontfamily.fontfamily": "Nét chữ",

    // FontSize
    "components.controls.fontsize.fontsize": "Cỡ chữ",

    // History
    "components.controls.history.history": "Lịch sử",
    "components.controls.history.undo": "Hoàn tác",
    "components.controls.history.redo": "Làm lại",

    // Image
    "components.controls.image.image": "Hình ảnh",
    "components.controls.image.fileUpload": "Tải lên tệp",
    "components.controls.image.byURL": "URL",
    "components.controls.image.dropFileText": "Thả tệp hoặc nhấp để tải lên",

    // Inline
    "components.controls.inline.bold": "In đậm",
    "components.controls.inline.italic": "Chữ in nghiêng",
    "components.controls.inline.underline": "Gạch chân",
    "components.controls.inline.strikethrough": "Gạch ngang",
    "components.controls.inline.monospace": "Monospace",
    "components.controls.inline.superscript": "Superscript",
    "components.controls.inline.subscript": "Subscript",

    // Link
    "components.controls.link.linkTitle": "Tiêu đề liên kết",
    "components.controls.link.linkTarget": "Mục tiêu liên kết",
    "components.controls.link.linkTargetOption": "Mở liên kết trong cửa sổ mới",
    "components.controls.link.link": "Liên kết",
    "components.controls.link.unlink": "Hủy liên kết",

    // List
    "components.controls.list.list": "Danh sách",
    "components.controls.list.unordered": "Danh sách không thứ tự",
    "components.controls.list.ordered": "Danh sách có thứ tự",
    "components.controls.list.indent": "Thụt lề",
    "components.controls.list.outdent": "Bỏ thụt lề",

    // Remove
    "components.controls.remove.remove": "Xóa",

    // TextAlign
    "components.controls.textalign.textalign": "Căn chỉnh văn bản",
    "components.controls.textalign.left": "Căn trái",
    "components.controls.textalign.center": "Căn giữa",
    "components.controls.textalign.right": "Căn phải",
    "components.controls.textalign.justify": "Căn đều",
  },
  ALL_ROLE_NAME: {
    ACTION_LOG_VIEW: "ACTION_LOG_VIEW",
    ADMIN_PERMISSIONS_CREATE_UPDATE: "ADMIN_PERMISSIONS_CREATE_UPDATE",
    ANNOUNCE_CATEGORY_CREATE_UPDATE: "ANNOUNCE_CATEGORY_CREATE_UPDATE",
    ANNOUNCE_CATEGORY_LIST: "ANNOUNCE_CATEGORY_LIST",
    ANNOUNCE_CREATE_UPDATE: "ANNOUNCE_CREATE_UPDATE",
    ANNOUNCE_LIST: "ANNOUNCE_LIST",
    ANNOUNCE_MANAGENMENT_CAMPAIGN_NOTIFY:
      "ANNOUNCE_MANAGENMENT_CAMPAIGN_NOTIFY",
    APARTMENT_CREATE_UPDATE: "APARTMENT_CREATE_UPDATE",
    APARTMENT_LIST: "APARTMENT_LIST",
    BASIC: "BASIC",
    BOOKING_MANAGER: "BOOKING_MANAGER",
    BUILDING_PERSONNEL_MANAGEMENT_CHANGE_STATUS:
      "BUILDING_PERSONNEL_MANAGEMENT_CHANGE_STATUS",
    BUILDING_PERSONNEL_MANAGEMENT_CREATE:
      "BUILDING_PERSONNEL_MANAGEMENT_CREATE",
    BUILDING_PERSONNEL_MANAGEMENT_DELETE:
      "BUILDING_PERSONNEL_MANAGEMENT_DELETE",
    BUILDING_PERSONNEL_MANAGEMENT_DETAIL:
      "BUILDING_PERSONNEL_MANAGEMENT_DETAIL",
    BUILDING_PERSONNEL_MANAGEMENT_EXPORT:
      "BUILDING_PERSONNEL_MANAGEMENT_EXPORT",
    BUILDING_PERSONNEL_MANAGEMENT_IMPORT:
      "BUILDING_PERSONNEL_MANAGEMENT_IMPORT",
    BUILDING_PERSONNEL_MANAGEMENT_LIST: "BUILDING_PERSONNEL_MANAGEMENT_LIST",
    BUILDING_PERSONNEL_MANAGEMENT_SET_PASSWORD:
      "BUILDING_PERSONNEL_MANAGEMENT_SET_PASSWORD",
    BUILDING_PERSONNEL_MANAGEMENT_UPDATE:
      "BUILDING_PERSONNEL_MANAGEMENT_UPDATE",
    CONTRACTOR_MANAGEMENT_CREATE: "CONTRACTOR_MANAGEMENT_CREATE",
    CONTRACTOR_MANAGEMENT_DELETE: "CONTRACTOR_MANAGEMENT_DELETE",
    CONTRACTOR_MANAGEMENT_DETAIL: "CONTRACTOR_MANAGEMENT_DETAIL",
    CONTRACTOR_MANAGEMENT_LIST: "CONTRACTOR_MANAGEMENT_LIST",
    CONTRACTOR_MANAGEMENT_UPDATE: "CONTRACTOR_MANAGEMENT_UPDATE",
    DASHBOARD_APARTMENT: "DASHBOARD_APARTMENT",
    DASHBOARD_MAINTENANCE: "DASHBOARD_MAINTENANCE",
    DASHBOARD_FINANCE: "DASHBOARD_FINANCE",
    DASHBOARD_GENERAL: "DASHBOARD_GENERAL",
    DASHBOARD_REQUEST: "DASHBOARD_REQUEST",
    DASHBOARD_RESIDENT: "DASHBOARD_RESIDENT",
    FINANCE_ALL_FEE_MANAGER: "FINANCE_ALL_FEE_MANAGER",
    FINANCE_ALL_FEE_VIEW: "FINANCE_ALL_FEE_VIEW",
    FINANCE_CASH_BOOK: "FINANCE_CASH_BOOK",
    FINANCE_CREATE_BILL: "FINANCE_CREATE_BILL",
    FINANCE_DEBT: "FINANCE_DEBT",
    FINANCE_INVOICE_BILL: "FINANCE_INVOICE_BILL",
    FINANCE_MANAGERMENT_BILL: "FINANCE_MANAGERMENT_BILL",
    FINANCE_REVENUE_BY_MONTH: "FINANCE_REVENUE_BY_MONTH",
    FINANCE_SPECIAL_BILL: "FINANCE_SPECIAL_BILL",
    FINANCE_SPECIAL_INVOICE_BILL: "FINANCE_SPECIAL_INVOICE_BILL",
    FINANCE_VIEW_BILL: "FINANCE_VIEW_BILL",
    FINANCE_VIEW_INVOICE_BILL: "FINANCE_VIEW_INVOICE_BILL",
    FINANCE_NOTIFICATION_FEE_MANAGER: "FINANCE_NOTIFICATION_FEE_MANAGER",
    INFOMATION_SERVICE_VIEW: "INFOMATION_SERVICE_VIEW",
    MANAGE_FORM_REGISTRATION_MAINTAIN_DEVICE_CONFIRMATION:
      "MANAGE_FORM_REGISTRATION_MAINTAIN_DEVICE_CONFIRMATION",
    MANAGE_FORM_REGISTRATION_MAINTAIN_DEVICE_CREATE:
      "MANAGE_FORM_REGISTRATION_MAINTAIN_DEVICE_CREATE",
    MANAGE_FORM_REGISTRATION_MAINTAIN_DEVICE_DETAIL:
      "MANAGE_FORM_REGISTRATION_MAINTAIN_DEVICE_DETAIL",
    MANAGE_FORM_REGISTRATION_MAINTAIN_DEVICE_LIST:
      "MANAGE_FORM_REGISTRATION_MAINTAIN_DEVICE_LIST",
    MANAGE_FORM_REGISTRATION_MAINTAIN_DEVICE_UPDATE:
      "MANAGE_FORM_REGISTRATION_MAINTAIN_DEVICE_UPDATE",
    MANAGE_FORM_REGISTRATION_MAINTAIN_DEVICE_EXPORT:
      "MANAGE_FORM_REGISTRATION_MAINTAIN_DEVICE_EXPORT",
    MANAGE_FORM_REGISTRATION_MAINTAIN_DEVICE_IMPORT:
      "MANAGE_FORM_REGISTRATION_MAINTAIN_DEVICE_IMPORT",
    MANAGE_FORM_REGISTRATION_SERVICE_UTILITY_FORM_CHANGESTATUS:
      "MANAGE_FORM_REGISTRATION_SERVICE_UTILITY_FORM_CHANGESTATUS",
    MANAGE_FORM_REGISTRATION_SERVICE_UTILITY_FORM_DETAIL:
      "MANAGE_FORM_REGISTRATION_SERVICE_UTILITY_FORM_DETAIL",
    MANAGE_FORM_REGISTRATION_SERVICE_UTILITY_FORM_LIST:
      "MANAGE_FORM_REGISTRATION_SERVICE_UTILITY_FORM_LIST",
    MANAGE_INVOICE_BILL: "MANAGE_INVOICE_BILL",
    REQUEST_DETAIL: "REQUEST_DETAIL",
    MANAGE_FORM_REGISTRATION_MAINTAIN_DEVICE_DELETE:
      "MANAGE_FORM_REGISTRATION_MAINTAIN_DEVICE_DELETE",
    MANAGE_FORM_REGISTRATION_MAINTAIN_DEVICE_EXPORT_SCHEDULE:
      "MANAGE_FORM_REGISTRATION_MAINTAIN_DEVICE_EXPORT_SCHEDULE",
    MANAGE_FORM_REGISTRATION_MAINTAIN_DEVICE_LIST_SCHEDULE:
      "MANAGE_FORM_REGISTRATION_MAINTAIN_DEVICE_LIST_SCHEDULE",
    MANAGE_GROUP_PERMISSIONS_RBAC_AUTH_GROUP_DELETE:
      "MANAGE_GROUP_PERMISSIONS_RBAC_AUTH_GROUP_DELETE",
    MANAGE_GROUP_PERMISSIONS_RBAC_AUTH_GROUPS:
      "MANAGE_GROUP_PERMISSIONS_RBAC_AUTH_GROUPS",
    MANAGE_GROUP_PERMISSIONS_RBAC_CREATE_AUTH_GROUP:
      "MANAGE_GROUP_PERMISSIONS_RBAC_CREATE_AUTH_GROUP",
    MANAGE_GROUP_PERMISSIONS_RBAC_UPDATE_AUTH_GROUP:
      "MANAGE_GROUP_PERMISSIONS_RBAC_UPDATE_AUTH_GROUP",
    NOTIFICATION_FORM_MANAGEMENT_CREATE: "NOTIFICATION_FORM_MANAGEMENT_CREATE",
    NOTIFICATION_FORM_MANAGEMENT_DELETE: "NOTIFICATION_FORM_MANAGEMENT_DELETE",
    NOTIFICATION_FORM_MANAGEMENT_DETAIL: "NOTIFICATION_FORM_MANAGEMENT_DETAIL",
    NOTIFICATION_FORM_MANAGEMENT_LIST_ITEM:
      "NOTIFICATION_FORM_MANAGEMENT_LIST_ITEM",
    NOTIFICATION_FORM_MANAGEMENT_UPDATE: "NOTIFICATION_FORM_MANAGEMENT_UPDATE",
    REAL_ESTATE_MANAGEMENT_CREATE: "REAL_ESTATE_MANAGEMENT_CREATE",
    REQUEST_CATEGORY_CREATE_UPDATE: "REQUEST_CATEGORY_CREATE_UPDATE",
    REAL_ESTATE_MANAGEMENT_DELETE: "REAL_ESTATE_MANAGEMENT_DELETE",
    REAL_ESTATE_MANAGEMENT_DETAIL: "REAL_ESTATE_MANAGEMENT_DETAIL",
    REAL_ESTATE_MANAGEMENT_EXPORT: "REAL_ESTATE_MANAGEMENT_EXPORT",
    REAL_ESTATE_MANAGEMENT_IMPORT: "REAL_ESTATE_MANAGEMENT_IMPORT",
    REAL_ESTATE_MANAGEMENT_LIST: "REAL_ESTATE_MANAGEMENT_LIST",
    REAL_ESTATE_MANAGEMENT_LIST_RESIDENT_USER:
      "REAL_ESTATE_MANAGEMENT_LIST_RESIDENT_USER",
    REAL_ESTATE_MANAGEMENT_UPDATE: "REAL_ESTATE_MANAGEMENT_UPDATE",
    REAL_ESTATE_MANAGEMENT_UPDATE_RESIDENT_USER:
      "REAL_ESTATE_MANAGEMENT_UPDATE_RESIDENT_USER",
    REAL_ESTATE_MANAGEMENT_CREATE_RESIDENT_USER:
      "REAL_ESTATE_MANAGEMENT_CREATE_RESIDENT_USER",
    REAL_ESTATE_MANAGEMENT_DELETE_RESIDENT_USER:
      "REAL_ESTATE_MANAGEMENT_DELETE_RESIDENT_USER",
    REQUEST_CATEGORY_LIST: "REQUEST_CATEGORY_LIST",
    REQUEST_CONTACT_RESIDENT: "REQUEST_CONTACT_RESIDENT",
    REQUEST_LIST: "REQUEST_LIST",
    REQUEST_MANAGER_GROUPS_PROCESS_ADMIN:
      "REQUEST_MANAGER_GROUPS_PROCESS_ADMIN",
    REQUEST_PROCESS: "REQUEST_PROCESS",
    RESIDENT_MANAGEMENT_CREATE: "RESIDENT_MANAGEMENT_CREATE",
    RESIDENT_MANAGEMENT_DELETE_APARTMENT_RESIDENT:
      "RESIDENT_MANAGEMENT_DELETE_APARTMENT_RESIDENT",
    RESIDENT_MANAGEMENT_DETAIL: "RESIDENT_MANAGEMENT_DETAIL",
    RESIDENT_MANAGEMENT_EXPORT: "RESIDENT_MANAGEMENT_EXPORT",
    RESIDENT_MANAGEMENT_IMPORT: "RESIDENT_MANAGEMENT_IMPORT",
    RESIDENT_MANAGEMENT_LIST: "RESIDENT_MANAGEMENT_LIST",
    RESIDENT_MANAGEMENT_UPDATE: "RESIDENT_MANAGEMENT_UPDATE",
    RESIDENT_OLD_LIST: "RESIDENT_OLD_LIST",
    RESOURCES_VIEW: "RESOURCES_VIEW",
    RIGHTS_GROUP_CREATE: "RIGHTS_GROUP_CREATE",
    RIGHTS_GROUP_UPDATE: "RIGHTS_GROUP_UPDATE",
    RIGHTS_GROUP_DELETE: "RIGHTS_GROUP_DELETE",
    SERVICE_CLOUD_ADD: "SERVICE_CLOUD_ADD",
    SERVICE_CLOUD_VIEW: "SERVICE_CLOUD_VIEW",
    SETTING_BUILDING_AREA_CREATE_UPDATE: "SETTING_BUILDING_AREA_CREATE_UPDATE",
    SETTING_BUILDING_INFOMATION: "SETTING_BUILDING_INFOMATION",
    SETTING_NOTIFICATION_FEE_MANAGER: "SETTING_NOTIFICATION_FEE_MANAGER",
    SETTING_RECEIVE_FINANCE_NOTIFICATION:
      "SETTING_RECEIVE_FINANCE_NOTIFICATION",
    SETTING_RESIDENT_BOOK: "SETTING_RESIDENT_BOOK",
    SETTING_SERVICE_MANAGERMENT: "SETTING_SERVICE_MANAGERMENT",
    SET_WIDGET_SERVICE_UTILITY_BOOKING_CHANGE_STATUS:
      "SET_WIDGET_SERVICE_UTILITY_BOOKING_CHANGE_STATUS",
    SET_WIDGET_SERVICE_UTILITY_BOOKING_CREATE:
      "SET_WIDGET_SERVICE_UTILITY_BOOKING_CREATE",
    SET_WIDGET_SERVICE_UTILITY_BOOKING_CREATE_INCURRED_FEE:
      "SET_WIDGET_SERVICE_UTILITY_BOOKING_CREATE_INCURRED_FEE",
    SET_WIDGET_SERVICE_UTILITY_BOOKING_DETAIL:
      "SET_WIDGET_SERVICE_UTILITY_BOOKING_DETAIL",
    SET_WIDGET_SERVICE_UTILITY_BOOKING_LIST:
      "SET_WIDGET_SERVICE_UTILITY_BOOKING_LIST",
    WORKFLOW_MANAGENMENT_GROUP: "WORKFLOW_MANAGENMENT_GROUP",
    WORKFLOW_MANAGENMENT_DETAIL: "WORKFLOW_MANAGENMENT_DETAIL",
    WORKFLOW_MANAGENMENT_LIST: "WORKFLOW_MANAGENMENT_LIST",
    CARD_MANAGEMENT_APPROVE: "CARD_MANAGEMENT_APPROVE",
    CARD_MANAGEMENT_CREATE: "CARD_MANAGEMENT_CREATE",
    CARD_MANAGEMENT_DELETE: "CARD_MANAGEMENT_DELETE",
    CARD_MANAGEMENT_DETAIL: "CARD_MANAGEMENT_DETAIL",
    CARD_MANAGEMENT_EXPORT: "CARD_MANAGEMENT_EXPORT",
    CARD_MANAGEMENT_IMPORT: "CARD_MANAGEMENT_IMPORT",
    CARD_MANAGEMENT_LIST: "CARD_MANAGEMENT_LIST",
    CARD_MANAGEMENT_RECALL: "CARD_MANAGEMENT_RECALL",
    CARD_MANAGEMENT_UPDATE: "CARD_MANAGEMENT_UPDATE",
  },
  ALL_GROUP_ROLE_NAME: {
    // ADMIN: "Quản trị phân quyền",
    // ANNOUNCE: "Quản lý bảng tin",
    // APARTMENT: "Quản lý bất động sản",
    BASIC: "Cơ bản",
    DASHBOARD: "Báo cáo tổng quan",
    FINANCE: "Quản lý tài chính",
    REQUEST: "Quản lý phản ánh",
    RESIDENT: "Quản lý cư dân",
    SERVICE: "Dịch vụ",
    SETTING: "Cấu hình dự án",
    // BOOKING: "Quản lý đặt chỗ",
    SERVICE_CLOUD: "Khởi tạo dịch vụ",
    MANAGE_FORM_REGISTRATION: "Quản lý đăng ký biểu mẫu",
    CONTRACTOR_MANAGEMENT: "Quản lý nhà thầu/nhà cung cấp",
    MANAGE_FORM_REGISTRATION_MAINTAIN_DEVICE: "Bảo trì thiết bị",
    WORKFLOW_MANAGENMENT: "Quản lý công việc",
    BUILDING_PERSONNEL_MANAGEMENT: "Quản lý nhân sự",
    RIGHTS_GROUP: "Quản lý nhóm quyền",
    NOTIFICATION_FORM_MANAGEMENT: "Quản lý bảng tin",
    REAL_ESTATE_MANAGEMENT: "Quản lý bất động sản",
    SET_WIDGET: "Quản lý đặt tiện ích",
    CARD_MANAGEMENT: "Quản lý thẻ hợp nhất",
  },
  ALL_GROUP_ROLE_NAME_EN: {
    BASIC: "Basic",
    DASHBOARD: "Overview report",
    FINANCE: "Financial management",
    REQUEST: "Feedback management",
    RESIDENT: "Resident management",
    SERVICE: "Service",
    SETTING: "Project configuration",
    // BOOKING: "Quản lý đặt chỗ",
    SERVICE_CLOUD: "Starting service",
    MANAGE_FORM_REGISTRATION: "E-form registration management",
    CONTRACTOR_MANAGEMENT: "Contractor/supplier management",
    MANAGE_FORM_REGISTRATION_MAINTAIN_DEVICE: "Equipment maintenance",
    WORKFLOW_MANAGENMENT: "Task management",
    BUILDING_PERSONNEL_MANAGEMENT: "Employee management",
    RIGHTS_GROUP: "Group authorization management",
    NOTIFICATION_FORM_MANAGEMENT: "Newsfeed management",
    REAL_ESTATE_MANAGEMENT: "Property management",
    SET_WIDGET: "Amenity booking management",
    CARD_MANAGEMENT: "CARD_MANAGEMENT",
  },
  ROUTERS: [
    {
      id: "/main",
      name: "Tổng quan",
      name_en: "Overview",
      description: "Tổng quan",
      description_en: "Overview",
      route: "/main",
      icon: "dashboard",
      denied: true,
    },
    {
      id: "/main/home",
      name: "Thống kê và báo cáo",
      name_en: "Statistics and reports",
      description: "Thống kê và báo cáo",
      description_en: "Statistics and reports",
      route: "/main/home",
      icon: "bar-chart",
      breadcrumbParentId: "/main",
      menuParentId: "/main",
      denied: true,
    },
    {
      id: "/main/infomation",
      name: "Thông tin dự án",
      name_en: "Project information",
      description: "Thông tin dự án",
      description_en: "Project information",
      route: "/main/infomation",
      icon: "ordered-list",
      breadcrumbParentId: "/main",
      menuParentId: "/main",
      denied: true,
    },
    {
      id: "/main/bookinglist/detail/:id/info",
      name: "Chi tiết đặt tiện ích",
      name_en: "Booking detail",
      route: "/main/bookinglist/detail/:id/info",
      description: "Chi tiết đặt tiện ích",
      description_en: "Booking detail",
      icon: "dashboard",
      breadcrumbParentId: "/main/bookinglist",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/bookinglist/add",
      name: "Tạo mới đặt chỗ",
      name_en: "Create new booking",
      route: "/main/bookinglist/add",
      description: "Tạo mới đặt chỗ",
      description_en: "Create new booking",
      icon: "dashboard",
      breadcrumbParentId: "/main/bookinglist",
      invisibleInMenu: true,
      main: true,
    },
    {
      id: "/main/apartment/list",
      name: "Bất động sản",
      name_en: "Property",
      description: "Danh sách bất động sản",
      description_en: "List of properties",
      route: "/main/apartment/list",
      icon: "shop",
      denied: true,
    },
    {
      id: "/main/apartment/add",
      name: "Thêm mới",
      name_en: "Add new",
      description: "Thêm mới bất động sản",
      description_en: "Add new property",
      route: "/main/apartment/add",
      breadcrumbParentId: "/main/apartment/list",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/apartment/detail/:id",
      name: "Chi tiết",
      name_en: "Detail",
      description: "Chi tiết bất động sản",
      description_en: "Detail property",
      route: "/main/apartment/detail/:id",
      breadcrumbParentId: "/main/apartment/list",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/resident/list",
      name: "Cư dân",
      name_en: "Resident",
      route: "/main/resident/list",
      description: "Danh sách cư dân",
      description_en: "List of residents",
      icon: "team",
      denied: true,
    },
    // {
    //   id: "/main/resident/list",
    //   name: "Danh sách",
    //   name_en: "List resident",
    //   description: "Danh sách cư dân hiện tại",
    //   description_en: "List current resident ",
    //   icon: "unordered-list",
    //   route: "/main/resident/list",
    //   breadcrumbParentId: "/main/resident",
    //   menuParentId: "/main/resident",
    //   denied: true,
    // },
    {
      id: "/main/resident/add",
      name: "Thêm mới",
      name_en: "Add new",
      description: "Thêm mới cư dân",
      description_en: "Add new resident",
      route: "/main/resident/add",
      breadcrumbParentId: "/main/resident/list",
      invisibleInMenu: true,
      denied: true,
    },
    // {
    //   id: "/main/resident-old/list",
    //   name: "Cư dân cũ",
    //   name_en: "Old resident",
    //   description: "Danh sách cư dân cũ",
    //   description_en: "List old resident",
    //   icon: "unordered-list",
    //   route: "/main/resident-old/list",
    //   breadcrumbParentId: "/main/resident",
    //   menuParentId: "/main/resident",
    //   denied: true,
    // },
    {
      id: "/main/resident/detail/:id",
      name: "Chi tiết cư dân",
      name_en: "Detail resident",
      description: "Chi tiết thông tin cư dân",
      description_en: "Detail resident",
      route: "/main/resident/detail/:id",
      breadcrumbParentId: "/main/resident/list",
      invisibleInMenu: true,
      denied: true,
    },
    // {
    //   id: "/main/resident-old/detail/:id",
    //   name: "Chi tiết cư dân cũ",
    //   name_en: "Detail old resident",
    //   description: "Chi tiết thông tin cư dân cũ",
    //   description_en: "Detail old resident",
    //   route: "/main/resident-old/detail/:id",
    //   breadcrumbParentId: "/main/resident-old/list",
    //   invisibleInMenu: true,
    //   denied: true,
    // },
    {
      id: "/main/finances",
      name: "Tài chính",
      name_en: "Finance",
      description: "Tài chính",
      description_en: "Finance",
      route: "/main/finances",
      icon: "dashboard",
      breadcrumbParentId: "/main",
      menuParentId: "/main",
      denied: true,
    },
    {
      id: "/main/finance/reception/bill/:id",
      name: "Phiếu thu",
      name_en: "Receipts",
      description: "Chi tiết phiếu thu",
      description_en: "Detail bill",
      route: "/main/finance/reception/bill/:id",
      icon: "dashboard",
      breadcrumbParentId: "/main/finance/reception",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/notification/list",
      name: "Bảng tin",
      name_en: "Newsfeed",
      route: "/main/notification/list",
      description: "Danh sách bảng tin",
      description_en: "List of news",
      icon: "notification",
      denied: true,
    },
    {
      id: "/main/notification/add/:id",
      name: "Tạo thông báo",
      name_en: "Create notification",
      route: "/main/notification/add/:id",
      description: "Tạo thông báo mới",
      description_en: "Create new notification",
      icon: "notification",
      breadcrumbParentId: "/main/notification/list",
      menuParentId: "/main/notification",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/notification/detail/:id",
      name: "Chi tiết",
      name_en: "Detail",
      route: "/main/notification/detail/:id",
      description: "Chi tiết bản tin",
      description_en: "Detail notification",
      icon: "tags",
      breadcrumbParentId: "/main/notification/list",
      menuParentId: "/main/notification",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/notification/edit/:id",
      name: "Chỉnh sửa",
      name_en: "Edit",
      route: "/main/notification/edit/:id",
      description: "Chỉnh sửa thông báo",
      description_en: "Edit notification",
      icon: "tags",
      breadcrumbParentId: "/main/notification/list",
      menuParentId: "/main/notification",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/ticket/list",
      name: "Phản ánh",
      name_en: "Feedback",
      route: "/main/ticket/list",
      description: "Danh sách phản ánh",
      description_en: "List feedbacks",
      icon: "message",
      denied: true,
    },
    // {
    //   id: "/main/ticket/category",
    //   name: "Danh mục",
    //   route: "/main/ticket/category",
    //   description: "Danh sách danh mục",
    //   icon: "tags",
    //   breadcrumbParentId: "/main/ticket",
    //   menuParentId: "/main/ticket",
    //   denied: true,
    // },
    {
      id: "/main/ticket/detail/:id",
      name: "Chi tiết",
      name_en: "Detail",
      route: "/main/ticket/detail/:id",
      description: "Chi tiết phản ánh",
      description_en: "Feedback details",
      icon: "tags",
      breadcrumbParentId: "/main/ticket/list",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/service/detail/generate",
      name: "Danh sách phí",
      name_en: "Fee list",
      route: "/main/service/detail/generate",
      description: "Tổng phí",
      description_en: "Total fee",
      icon: "unordered-list",
      breadcrumbParentId: "/main/finance",
      menuParentId: "/main/finance",
      denied: true,
    },
    {
      id: "/main/finance/revenue-by-month",
      name: "Doanh thu theo tháng",
      name_en: "Revenue by month",
      route: "/main/finance/revenue-by-month",
      description: "Doanh thu theo tháng",
      description_en: "Revenue by month",
      icon: "line-chart",
      breadcrumbParentId: "/main/finance",
      menuParentId: "/main/finance",
      denied: true,
    },
    {
      id: "/main/service/create/water",
      name: "Phí nước",
      name_en: "Water fee",
      route: "/main/service/create/water",
      description: "Tạo phí",
      description_en: "Create fee",
      icon: "unordered-list",
      breadcrumbParentId: "/main/service/create/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/service/create/electric",
      name: "Điện",
      name_en: "Electric",
      route: "/main/service/create/electric",
      description: "Tạo phí",
      description_en: "Create fee",
      icon: "unordered-list",
      breadcrumbParentId: "/main/service/create/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/service/create/moto-packing",
      name: "Gửi xe",
      name_en: "Motor parking fee",
      route: "/main/service/create/moto-packing",
      description: "Tạo phí",
      description_en: "Create fee",
      icon: "unordered-list",
      breadcrumbParentId: "/main/service/create/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/service/create/apartment-fee",
      name: "Phí dịch vụ",
      name_en: "Service fee",
      route: "/main/service/create/apartment-fee",
      description: "Tạo phí",
      description_en: "Create fee",
      icon: "unordered-list",
      breadcrumbParentId: "/main/service/create/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/service/create/old_debit",
      name: "Công nợ",
      name_en: "Outstanding liability",
      route: "/main/service/create/old_debit",
      description: "Tạo công nợ",
      description_en: "Create outstanding liability",
      icon: "unordered-list",
      breadcrumbParentId: "/main/service/create/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/service/detail/water",
      name: "Nước",
      name_en: "Water",
      route: "/main/service/detail/water",
      description: "Số nước đã duyệt",
      description_en: "Water approved",
      icon: "unordered-list",
      breadcrumbParentId: "/main/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/service/detail/water/usage",
      name: "Nước",
      name_en: "Water",
      route: "/main/service/detail/water/usage",
      description: "Sử dụng",
      description_en: "Water usage",
      icon: "unordered-list",
      breadcrumbParentId: "/main/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/service/detail/water/lock",
      name: "Nước",
      name_en: "Water",
      route: "/main/service/detail/water/lock",
      description: "Số nước đã duyệt",
      description_en: "Water approved",
      icon: "unordered-list",
      breadcrumbParentId: "/main/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/service/detail/water/lock-template",
      name: "Nước",
      name_en: "Water",
      route: "/main/service/detail/water/lock-template",
      description: "Số nước chưa duyệt",
      description_en: "Water not approved",
      icon: "unordered-list",
      breadcrumbParentId: "/main/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/service/detail/old_debit",
      name: "Nợ cũ",
      name_en: "Outstanding liability",
      route: "/main/service/detail/old_debit",
      description: "Thông tin dịch vụ",
      description_en: "Service information",
      icon: "unordered-list",
      breadcrumbParentId: "/main/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/service/detail/old_debit/lock",
      name: "Nợ cũ",
      name_en: "Outstanding liability",
      route: "/main/service/detail/old_debit/lock",
      description: "Nợ cũ đã duyệt",
      description_en: "Approved liability",
      icon: "unordered-list",
      breadcrumbParentId: "/main/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/service/detail/old_debit/lock-template",
      name: "Nợ cũ",
      name_en: "Outstanding liability",
      route: "/main/service/detail/old_debit/lock-template",
      description: "Nợ cũ chưa duyệt",
      description_en: "Awaiting approval",
      icon: "unordered-list",
      breadcrumbParentId: "/main/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/service/detail/electric",
      name: "Điện",
      name_en: "Electric",
      route: "/main/service/detail/electric",
      description: "Sử dụng",
      description_en: "Electric usage",
      icon: "unordered-list",
      breadcrumbParentId: "/main/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/service/detail/electric/usage",
      name: "Điện",
      name_en: "Electric",
      route: "/main/service/detail/electric/usage",
      description: "Sử dụng",
      description_en: "Electric usage",
      icon: "unordered-list",
      breadcrumbParentId: "/main/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/service/detail/electric/lock",
      name: "Điện",
      name_en: "Electric",
      route: "/main/service/detail/electric/lock",
      description: "Số điện đã duyệt",
      description_en: "Electric approved",
      icon: "unordered-list",
      breadcrumbParentId: "/main/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/service/detail/electric/lock-template",
      name: "Điện",
      name_en: "Electric",
      route: "/main/service/detail/electric/lock-template",
      description: "Số điện chưa duyệt",
      description_en: "Electric not approved",
      icon: "unordered-list",
      breadcrumbParentId: "/main/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },

    {
      id: "/main/service/detail/moto-packing",
      name: "Gửi xe",
      name_en: "Motor parking",
      route: "/main/service/detail/moto-packing",
      description: "Quản lý xe",
      description_en: "Vehicle management",
      icon: "unordered-list",
      breadcrumbParentId: "/main/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/service/detail/moto-packing/vehicle",
      name: "Gửi xe",
      name_en: "Motor parking",
      route: "/main/service/detail/moto-packing/vehicle",
      description: "Quản lý xe",
      description_en: "Vehicle management",
      icon: "unordered-list",
      breadcrumbParentId: "/main/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/service/detail/moto-packing/lock",
      name: "Gửi xe",
      name_en: "Motor parking",
      route: "/main/service/detail/moto-packing/lock",
      description: "Phí xe đã duyệt",
      description_en: "Motor parking approved",
      icon: "unordered-list",
      breadcrumbParentId: "/main/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/service/detail/moto-packing/lock-template",
      name: "Gửi xe",
      name_en: "Motor parking",
      route: "/main/service/detail/moto-packing/lock-template",
      description: "Phí xe chờ duyệt",
      description_en: "Motor parking not approved",
      icon: "unordered-list",
      breadcrumbParentId: "/main/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/service/detail/apartment-fee",
      name: "Quản lý toà nhà",
      name_en: "Building management",
      route: "/main/service/detail/apartment-fee",
      description: "Thông tin dịch vụ",
      description_en: "Service information",
      icon: "unordered-list",
      breadcrumbParentId: "/main/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/service/detail/apartment-fee/usage",
      name: "Phí quản lý",
      name_en: "Management fee",
      route: "/main/service/detail/apartment-fee/usage",
      description: "Sử dụng",
      description_en: "Usage",
      icon: "unordered-list",
      breadcrumbParentId: "/main/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/service/detail/apartment-fee/payment",
      name: "Quản lý toà nhà",
      name_en: "Management fee",
      route: "/main/service/detail/apartment-fee/payment",
      description: "Phí đã duyệt",
      description_en: "Fee approved",
      icon: "unordered-list",
      breadcrumbParentId: "/main/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/service/detail/apartment-fee/payment-template",
      name: "Quản lý toà nhà",
      name_en: "Management fee",
      route: "/main/service/detail/apartment-fee/payment-template",
      description: "Phí chờ duyệt",
      description_en: "Awaiting approval",
      icon: "unordered-list",
      breadcrumbParentId: "/main/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/service/detail/utility-free",
      name: "Tiện ích",
      name_en: "Amenity",
      route: "/main/service/detail/utility-free",
      description: "Danh sách phí",
      description_en: "Fee list",
      icon: "unordered-list",
      breadcrumbParentId: "/main/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/service/detail/utility-free/booking-fee-list",
      name: "Tiện ích",
      name_en: "Amenity",
      route: "/main/service/detail/utility-free/booking-fee-list",
      description: "Danh sách phí",
      description_en: "Fee list",
      icon: "unordered-list",
      breadcrumbParentId: "/main/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/service/detail/fees",
      name: "Tổng phí",
      name_en: "Total fee",
      route: "/main/service/detail/fees",
      description: "Tổng phí",
      description_en: "Total fee",
      icon: "euro",
      breadcrumbParentId: "/main/service/detail/generate",
      invisibleInMenu: true,
      main: true,
    },
    // {
    //   id: "/main/service/providers",
    //   name: "Nhà cung cấp",
    //   route: "/main/service/providers",
    //   description: "Danh sách nhà cung cấp dịch vụ",
    //   icon: "solution",
    //   breadcrumbParentId: "/main/service",
    //   menuParentId: "/main/service",
    //   denied: true,
    // },
    // {
    //   id: "/main/service/providers/add",
    //   name: "Thêm mới",
    //   route: "/main/service/providers/add",
    //   description: "Thêm mới nhà cung cấp dịch vụ",
    //   icon: "unordered-list",
    //   breadcrumbParentId: "/main/service/providers",
    //   invisibleInMenu: true,
    //   denied: true,
    // },
    // {
    //   id: "/main/service/providers/detail/:id",
    //   name: "Chi tiết",
    //   route: "/main/service/providers/detail/:id",
    //   description: "Chi tiết nhà cung cấp dịch vụ",
    //   icon: "unordered-list",
    //   breadcrumbParentId: "/main/service/providers",
    //   invisibleInMenu: true,
    //   denied: true,
    // },
    {
      id: "/main/bookinglist",
      name: "Đặt tiện ích",
      name_en: "Booking",
      description: "Danh sách đặt tiện ích",
      description_en: "List of bookings",
      route: "/main/bookinglist",
      icon: "clock-circle",
      denied: true,
    },
    {
      id: "/main/service-utility-form/list",
      name: "Biểu mẫu",
      name_en: "E-form",
      route: "/main/service-utility-form/list",
      description: "Danh sách đăng ký biểu mẫu",
      description_en: "List of E-form registration",
      icon: "form",
      denied: false,
    },
    {
      id: "/main/service-utility-form/detail/:id",
      name: "Chi tiết",
      name_en: "Detail",
      description: "Chi tiết đăng ký biểu mẫu",
      description_en: "Details of registration form",
      route: "/main/service-utility-form/detail/:id",
      breadcrumbParentId: "/main/service-utility-form/list",
      invisibleInMenu: true,
    },
    {
      id: "/main/account/settings/language",
      name: "Cá nhân / Ngôn ngữ",
      name_en: "Personal / Language",
      description: "Ngôn ngữ hệ thống",
      description_en: "System language",
      route: "/main/account/settings/language",
      breadcrumbParentId: "/main",
      invisibleInMenu: true,
      main: true,
    },
    {
      id: "/main/setting/building/staff/detail/:id",
      name: "Nhân sự / Chi tiết nhân sự",
      name_en: "Employee / Detail employee",
      description: "Chi tiết nhân sự",
      description_en: "Detail employee",
      route: "/main/setting/building/staff/detail/:id",
      breadcrumbParentId: "/main/setting/building",
      invisibleInMenu: true,
    },
    {
      id: "/main/contractor/list",
      name: "Nhà thầu",
      name_en: "Contractor",
      route: "/main/contractor/list",
      description: "Danh sách nhà thầu",
      description_en: "List of contractors",
      icon: "home",
    },
    {
      id: "/main/contractor/detail/:id",
      name: "Chi tiết nhà thầu",
      name_en: "Detail contractor",
      description: "Chi tiết nhà thầu",
      description_en: "Detail contractor",
      route: "/main/contractor/detail/:id",
      breadcrumbParentId: "/main/contractor/list",
      invisibleInMenu: true,
    },
    {
      id: "/main/contractor/add",
      name: "Thêm mới nhà thầu",
      name_en: "Add contractor",
      description: "Thêm mới nhà thầu",
      description_en: "Add contractor",
      route: "/main/contractor/add",
      breadcrumbParentId: "/main/contractor/list",
      invisibleInMenu: true,
    },
    {
      id: "/main/contractor/edit/:id",
      name: "Chỉnh sửa nhà thầu",
      name_en: "Edit contractor",
      description: "Chỉnh sửa nhà thầu",
      description_en: "Edit contractor",
      route: "/main/contractor/edit/:id",
      breadcrumbParentId: "/main/contractor/list",
      invisibleInMenu: true,
    },
    {
      id: "/main/task/list",
      name: "Công việc",
      name_en: "Task",
      route: "/main/task/list",
      description: "Danh sách công việc",
      description_en: "List of tasks",
      icon: "project",
      denied: false,
    },
    {
      id: "/main/task/add",
      name: "Thêm mới công việc",
      name_en: "Add task",
      description: "Thêm mới công việc",
      description_en: "Add task",
      route: "/main/task/add",
      breadcrumbParentId: "/main/task/list",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/task/edit/:id",
      name: "Chỉnh sửa công việc",
      name_en: "Edit task",
      description: "Chỉnh sửa công việc",
      description_en: "Edit task",
      route: "/main/task/edit/:id",
      breadcrumbParentId: "/main/task/list",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/task/detail/:id",
      name: "Chi tiết công việc",
      name_en: "Detail task",
      route: "/main/task/detail/:id",
      description: "Chi tiết công việc",
      description_en: "Detail task",
      icon: "project",
      denied: false,
      breadcrumbParentId: "/main/task/list",
      invisibleInMenu: true,
    },
    {
      id: "/main/maintain/list",
      name: "Bảo trì thiết bị",
      name_en: "Equipment maintenance",
      route: "/main/maintain/list",
      description: "Bảo trì thiết bị",
      description_en: "Equipment maintenance",
      icon: "tool",
      denied: false,
    },
    {
      id: "/main/maintain/detail/:id",
      name: "Chi tiết",
      name_en: "Detail",
      description: "Chi tiết thiết bị",
      description_en: "Detail equipment",
      route: "/main/maintain/detail/:id",
      breadcrumbParentId: "/main/maintain/list",
      invisibleInMenu: true,
    },
    {
      id: "/main/maintain/edit/:id",
      name: "Chỉnh sửa",
      name_en: "Edit",
      description: "Chỉnh sửa thiết bị",
      description_en: "Edit equipment",
      route: "/main/maintain/edit/:id",
      breadcrumbParentId: "/main/maintain/list",
      invisibleInMenu: true,
    },
    {
      id: "/main/maintain/add",
      name: "Tạo mới",
      name_en: "Create",
      description: "Tạo mới thiết bị",
      description_en: "Create new equipment",
      route: "/main/maintain/add",
      breadcrumbParentId: "/main/maintain/list",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/merge-card/list",
      name: "Thẻ hợp nhất",
      name_en: "Merge card",
      route: "/main/merge-card/list",
      description: "Danh sách thẻ hợp nhất",
      description_en: "List of merge card",
      icon: "idcard",
      denied: false,
    },
    {
      id: "/main/merge-card/detail/:id",
      name: "Chi tiết thẻ",
      name_en: "Detail card",
      route: "/main/merge-card/detail/:id",
      description: "Chi tiết thẻ",
      description_en: "Detail card",
      breadcrumbParentId: "/main/merge-card/list",
      invisibleInMenu: true,
    },
    {
      id: "/main/finance/payment-request/detail/:id",
      name: "Chi tiết xác nhận thanh toán",
      name_en: "Detail payment request",
      description: "Chi tiết xác nhận thanh toán",
      description_en: "Detail payment request",
      route: "/main/finance/payment-request/detail/:id",
      breadcrumbParentId: "/main/finance/bills",
      invisibleInMenu: true,
    },
    {
      id: "/main/notification/add/:id",
      name: "Tạo bản tin",
      name_en: "Create news",
      route: "/main/notification/add/:id",
      description: "Tạo bản tin",
      description_en: "Create news",
      icon: "notification",
      breadcrumbParentId: "/main/notification/list",
      menuParentId: "/main/notification",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/finance",
      name: "Tài chính",
      name_en: "Finance",
      route: "/main/finance",
      description: "Quản lý tài chính",
      description_en: "Finance management",
      icon: "bank",
      denied: true,
    },

    {
      id: "/main/finance/notification-fee/list",
      name: "Thông báo phí",
      name_en: "Fee notification",
      route: "/main/finance/notification-fee/list",
      description: "Danh sách thông báo phí",
      description_en: "List of fee notifications",
      icon: "snippets",
      breadcrumbParentId: "/main/finance",
      menuParentId: "/main/finance",
      denied: true,
    },
    {
      id: "/main/finance/notification-fee/add",
      name: "Tạo mới thông báo phí",
      name_en: "Create notification fee",
      route: "/main/finance/notification-fee/add",
      description: "Tạo mới thông báo phí",
      description_en: "Create notification fee",
      icon: "snippets",
      breadcrumbParentId: "/main/finance/notification-fee/list",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/finance/notification-fee/detail/:id",
      name: "Chi tiết",
      name_en: "Detail",
      route: "/main/finance/notification-fee/detail/:id",
      description: "Chi tiết thông báo phí",
      description_en: "Detail notification fee",
      icon: "snippets",
      breadcrumbParentId: "/main/finance/notification-fee/list",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/finance/notification-fee/edit/:id",
      name: "Chỉnh sửa",
      name_en: "Edit",
      route: "/main/finance/notification-fee/edit/:id",
      description: "Chỉnh sửa thông báo",
      description_en: "Edit notification",
      icon: "snippets",
      breadcrumbParentId: "/main/finance/notification-fee/list",
      invisibleInMenu: true,
      denied: true,
    },
    // {
    //   id: "/main/finance/fees",
    //   name: "Danh sách phí",
    //   route: "/main/finance/fees",
    //   description: "Danh sách phí",
    //   icon: "euro",
    //   breadcrumbParentId: "/main/finance",
    //   menuParentId: "/main/finance",
    //   denied: true,
    // },
    {
      id: "/main/finance/reception",
      name: "Thu phí",
      name_en: "Create receipts",
      description: "Thu phí",
      description_en: "Create a receipts",
      route: "/main/finance/reception",
      icon: "transaction",
      breadcrumbParentId: "/main/finance",
      menuParentId: "/main/finance",
      denied: true,
    },
    {
      id: "/main/finance/bills",
      name: "Phiếu thu",
      name_en: "Receipts",
      route: "/main/finance/bills",
      description: "Danh sách phiếu thu",
      description_en: "List of receipts",
      icon: "unordered-list",
      breadcrumbParentId: "/main/finance",
      menuParentId: "/main/finance",
      denied: true,
    },
    // Phiếu chi
    {
      id: "/main/finance/invoice-bill",
      name: "Tạo phiếu chi",
      name_en: "Create payment vouchers",
      description: "Tạo phiếu chi",
      description_en: "Create payment vouchers",
      route: "/main/finance/invoice-bill",
      icon: "transaction",
      breadcrumbParentId: "/main/finance",
      menuParentId: "/main/finance",
      denied: true,
    },
    {
      id: "/main/finance/invoice-bill/bill/:id",
      name: "Phiếu chi",
      name_en: "Payment vouchers",
      description: "Chi tiết phiếu chi",
      description_en: "Detail invoice bill",
      route: "/main/finance/invoice-bill/bill/:id",
      icon: "transaction",
      breadcrumbParentId: "/main/finance/invoice-bill",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/finance/invoice-bills",
      name: "Phiếu chi",
      name_en: "Payment vouchers",
      route: "/main/finance/invoice-bills",
      description: "Danh sách phiếu chi",
      description_en: "List of payment vouchers",
      icon: "unordered-list",
      breadcrumbParentId: "/main/finance",
      menuParentId: "/main/finance",
      denied: true,
    },
    {
      id: "/main/finance/invoice-bills-cancel",
      name: "Phiếu huỷ",
      name_en: "Voided payment vouchers",
      route: "/main/finance/invoice-bills-cancel",
      description: "Danh sách phiếu huỷ",
      description_en: "List of voided vouchers",
      icon: "transaction",
      breadcrumbParentId: "/main/finance/invoice-bills",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/finance/invoice-bills/detail/:id",
      name: "Phiếu chi",
      name_en: "Payment vouchers",
      route: "/main/finance/invoice-bills/detail/:id",
      description: "Chi tiết phiếu chi",
      description_en: "Detail invoice bill",
      icon: "euro",
      breadcrumbParentId: "/main/finance/invoice-bills",
      invisibleInMenu: true,
      denied: true,
    },
    // End phiếu chi

    {
      id: "/main/finance/payment-request",
      name: "Xác nhận thanh toán",
      name_en: "Payment request",
      route: "/main/finance/payment-request",
      description: "Danh sách xác nhận thanh toán",
      description_en: "List of payment request confirmation",
      icon: "transaction",
      breadcrumbParentId: "/main/finance/bills",
      // menuParentId: "/main/finance",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/finance/cashbook",
      name: "Sổ quỹ",
      name_en: "Cashbook",
      route: "/main/finance/cashbook",
      description: "Sổ quỹ",
      description_en: "Cashbook",
      icon: "transaction",
      breadcrumbParentId: "/main/finance",
      menuParentId: "/main/finance",
      denied: true,
    },
    {
      id: "/main/finance/bills-cancel",
      name: "Phiếu huỷ",
      name_en: "Voided receipts",
      route: "/main/finance/bills-cancel",
      description: "Danh sách phiếu huỷ",
      description_en: "List of voided receipts",
      icon: "transaction",
      breadcrumbParentId: "/main/finance/bills",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/finance/debt-all",
      name: "Công nợ",
      name_en: "Liabilities",
      route: "/main/finance/debt-all",
      description: "Danh sách công nợ",
      description_en: "List of liabilities",
      icon: "transaction",
      breadcrumbParentId: "/main/finance",
      menuParentId: "/main/finance",
      denied: true,
    },
    {
      id: "/main/finance/debt",
      name: "Công nợ",
      name_en: "Liabilities",
      route: "/main/finance/debt",
      description: "Danh sách công nợ",
      description_en: "List of liabilities",
      icon: "transaction",
      breadcrumbParentId: "/main/finance/debt-all",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/finance/bills/detail/:id",
      name: "Phiếu thu",
      name_en: "Receipts",
      route: "/main/finance/bills/detail/:id",
      description: "Chi tiết phiếu thu",
      description_en: "Detail bill",
      icon: "euro",
      breadcrumbParentId: "/main/finance/bills",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/history",
      name: "Lịch sử vào ra",
      name_en: "History",
      route: "/main/history",
      description: "Trang chủ",
      description_en: "Home",
      icon: "history",
      denied: true,
    },
    {
      id: "/main/history/carpacking",
      name: "Gửi xe",
      name_en: "Car parking",
      description: "Gửi xe",
      description_en: "Car parking",
      icon: "unordered-list",
      route: "/main/history/carpacking",
      breadcrumbParentId: "/main/history",
      menuParentId: "/main/history",
      denied: true,
    },
    {
      id: "/main/history/accesscontrol",
      name: "Access control",
      name_en: "Access control",
      description: "Access control",
      description_en: "Access control",
      icon: "unordered-list",
      route: "/main/history/accesscontrol",
      breadcrumbParentId: "/main/history",
      menuParentId: "/main/history",
      denied: true,
    },
    // {
    //   id: "/main/lucid",
    //   name: "Quản lý thẻ",
    //   name_en: "Card management",
    //   route: "/main/lucid",
    //   description: "Trang chủ",
    //   description_en: "Home",
    //   icon: "idcard",
    //   denied: true,
    // },
    // {
    //   id: "/main/lucid/list",
    //   name: "Danh sách",
    //   name_en: "List",
    //   description: "Danh sách thẻ hợp nhất",
    //   description_en: "List card",
    //   icon: "unordered-list",
    //   route: "/main/lucid/list",
    //   breadcrumbParentId: "/main/lucid",
    //   menuParentId: "/main/lucid",
    //   denied: true,
    // },
    {
      id: "/main/setting",
      name: "Cấu hình",
      name_en: "Setting",
      route: "/main/setting",
      icon: "setting",
    },

    //============ Building Infomation ===============//
    {
      id: "/main/setting/building",
      name: "Dự án",
      name_en: "Project",
      description: "Cấu hình cấu trúc dự án",
      description_en: "Configure project structure",
      route: "/main/setting/building",
      breadcrumbParentId: "/main/setting",
      menuParentId: "/main/setting",
      icon: "home",
      // main: true,
      // denied: true,
    },
    {
      id: "/main/setting/building/infomation",
      name: "Thông tin",
      name_en: "Information",
      description: "Thông tin dự án",
      description_en: "Project information",
      route: "/main/setting/building/infomation",
      breadcrumbParentId: "/main/setting/building",
      menuParentId: "/main/setting/building",
      icon: "home",
      // denied: true,
    },
    {
      id: "/main/setting/building/plane",
      name: "Mặt bằng",
      name_en: "Structure",
      description: "Thông tin mặt bằng",
      description_en: "Structure information",
      route: "/main/setting/building/plane",
      breadcrumbParentId: "/main/setting/building",
      menuParentId: "/main/setting/building",
      icon: "home",
      // denied: true,
    },
    {
      id: "/main/setting/building/staff/list",
      name: "Nhân sự",
      name_en: "Employee",
      description: "Danh sách nhân sự",
      description_en: "Employee list",
      route: "/main/setting/building/staff/list",
      breadcrumbParentId: "/main/setting/building",
      menuParentId: "/main/setting/building",
      icon: "user",
      // denied: true,
    },

    {
      id: "/main/setting/building/staff/add",
      name: "Nhân sự / Thêm mới nhân sự",
      name_en: "Employee / Add employee",
      description: "Thêm mới nhân sự",
      description_en: "Add employee",
      route: "/main/setting/building/staff/add",
      breadcrumbParentId: "/main/setting/building",
      menuParentId: "/main/setting/building",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/setting/building/staff/edit/:id",
      name: "Nhân sự / Cập nhật nhân sự",
      name_en: "Employee / Edit employee",
      description: "Chỉnh sửa thông tin nhân sự",
      description_en: "Edit employee infomation",
      route: "/main/setting/building/staff/edit/:id",
      breadcrumbParentId: "/main/setting/building",
      menuParentId: "/main/setting/building",
      invisibleInMenu: true,
      denied: true,
    },
    //==================== End =========================//

    //==================== Roles =================//
    {
      id: "/main/setting/roles",
      name: "Phân quyền",
      name_en: "Authorization ",
      description: "Danh sách nhóm quyền",
      description_en: "List of authorization groups",
      route: "/main/setting/roles/list",
      icon: "usergroup-add",
      breadcrumbParentId: "/main/setting",
      menuParentId: "/main/setting",
      // main: true,
    },
    {
      id: "/main/setting/roles/list",
      name: "Nhân sự",
      name_en: "Employee",
      description: "Danh sách nhóm quyền nhân sự",
      description_en: "List of authorizing groups",
      route: "/main/setting/roles/list",
      icon: "usergroup-add",
      breadcrumbParentId: "/main/setting/roles",
      menuParentId: "/main/setting/roles",
      // main: true,
    },
    {
      id: "/main/setting/roles/create",
      name: "Thêm mới nhóm quyền",
      name_en: "Add new group",
      description: "Thêm mới nhóm quyền",
      description_en: "Add new group",
      route: "/main/setting/roles/create",
      icon: "usergroup-add",
      breadcrumbParentId: "/main/setting/roles",
      menuParentId: "/main/setting/roles",
      invisibleInMenu: true,
      // main: true,
    },
    {
      id: "/main/setting/roles/edit/:id",
      name: "Chỉnh sửa nhóm quyền",
      name_en: "Edit roles",
      description: "Chỉnh sửa nhóm quyền",
      description_en: "Edit roles",
      route: "/main/setting/roles/edit/:id",
      icon: "usergroup-add",
      breadcrumbParentId: "/main/setting/roles",
      menuParentId: "/main/setting/roles",
      invisibleInMenu: true,
      // main: true,
    },
    {
      id: "/main/setting/roles/finance-notify",
      name: "Tài chính",
      name_en: "Finance",
      description: "Danh sách nhóm nhận thông báo về tài chính",
      description_en: "Finance roles list",
      route: "/main/setting/roles/finance-notify",
      icon: "user",
      breadcrumbParentId: "/main/setting/roles",
      menuParentId: "/main/setting/roles",
      titleTooltip:
        "Các nhóm quyền này sẽ nhận được thông báo khi có phát sinh: Tạo phí tự động, có hoá đơn mới tạo từ người dùng.",
      titleTooltip_en:
        "These roles will receive notifications when they arise: Automatic fee generation, with new invoices created from users.",
      // denied: true,
    },
    //==================== End =========================//

    //==================== Notification =================//

    {
      id: "/main/setting/notify",
      name: "Bảng tin",
      name_en: "Newsfeed",
      description: "Cấu hình bảng tin",
      description_en: "Newsfeed setting",
      route: "/main/setting/notify",
      breadcrumbParentId: "/main/setting",
      menuParentId: "/main/setting",
      icon: "notification",
      denied: true,
    },
    {
      id: "/main/setting/notify/category",
      name: "Danh mục",
      name_en: "Category",
      route: "/main/setting/notify/category",
      description: "Danh sách danh mục",
      description_en: "Category list",
      icon: "tags",
      breadcrumbParentId: "/main/setting/notify",
      menuParentId: "/main/setting/notify",
      denied: true,
    },

    //======================= End =====================//

    //======================= Setting Ticket===================//
    {
      id: "/main/setting/ticket",
      name: "Phản ánh",
      name_en: "Feedback",
      description: "Cấu hình phản ánh",
      description_en: "Feedback setting",
      route: "/main/setting/ticket/category",
      breadcrumbParentId: "/main/setting",
      menuParentId: "/main/setting",
      icon: "message",
      denied: true,
    },
    {
      id: "/main/setting/ticket/category",
      name: "Danh mục",
      name_en: "Category",
      route: "/main/setting/ticket/category",
      description: "Danh sách danh mục",
      description_en: "Category list",
      icon: "tags",
      breadcrumbParentId: "/main/setting/ticket",
      menuParentId: "/main/setting/ticket",
      denied: true,
    },
    //=======================  End ===================//

    //===============Setting Service===============//

    {
      id: "/main/setting/service/detail/generate",
      name: "Dịch vụ",
      name_en: "Service",
      route: "/main/setting/service/detail/generate",
      description: "Thông tin dịch vụ",
      description_en: "Service information",
      icon: "reconciliation",
      breadcrumbParentId: "/main/setting",
      menuParentId: "/main/setting",
      denied: true,
    },
    {
      id: "/main/setting/service/detail/water",
      name: "Dịch vụ",
      name_en: "Service",
      route: "/main/setting/service/detail/water",
      description: "Thông tin dịch vụ",
      description_en: "Service information",
      icon: "reconciliation",
      breadcrumbParentId: "/main/setting/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/setting/service/detail/water/infomation",
      name: "Nước",
      name_en: "Water",
      route: "/main/setting/service/detail/water/infomation",
      description: "Thông tin dịch vụ",
      description_en: "Service information",
      icon: "cluster",
      breadcrumbParentId: "/main/setting/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/setting/service/detail/water/setup-fee",
      name: "Nước",
      name_en: "Water",
      route: "/main/setting/service/detail/water/setup-fee",
      description: "Cài đặt mức phí",
      description_en: "Setup fee",
      icon: "cluster",
      breadcrumbParentId: "/main/setting/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/setting/service/detail/old_debit",
      name: "Nợ cũ",
      name_en: "Outstanding liability",
      route: "/main/setting/service/detail/old_debit",
      description: "Thông tin dịch vụ",
      description_en: "Service information",
      icon: "cluster",
      breadcrumbParentId: "/main/setting/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/setting/service/detail/old_debit/infomation",
      name: "Nợ cũ",
      name_en: "Outstanding liability",
      route: "/main/setting/service/detail/old_debit/infomation",
      description: "Thông tin dịch vụ",
      description_en: "Service information",
      icon: "cluster",
      breadcrumbParentId: "/main/setting/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/setting/service/detail/electric",
      name: "Điện",
      name_en: "Electric",
      route: "/main/setting/service/detail/electric",
      description: "Thông tin dịch vụ",
      description_en: "Service information",
      icon: "cluster",
      breadcrumbParentId: "/main/setting/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/setting/service/detail/electric/infomation",
      name: "Điện",
      name_en: "Electric",
      route: "/main/setting/service/detail/electric/infomation",
      description: "Thông tin dịch vụ",
      description_en: "Service information",
      icon: "cluster",
      breadcrumbParentId: "/main/setting/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/setting/service/detail/electric/setup-fee",
      name: "Điện",
      name_en: "Electric",
      route: "/main/setting/service/detail/electric/setup-fee",
      description: "Cài đặt mức phí",
      description_en: "Setup fee",
      icon: "cluster",
      breadcrumbParentId: "/main/setting/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/setting/service/detail/moto-packing",
      name: "Gửi xe",
      name_en: "Motor parking",
      route: "/main/setting/service/detail/moto-packing",
      description: "Thông tin dịch vụ",
      description_en: "Service information",
      icon: "cluster",
      breadcrumbParentId: "/main/setting/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/setting/service/detail/moto-packing/infomation",
      name: "Gửi xe",
      name_en: "Motor parking",
      route: "/main/setting/service/detail/moto-packing/infomation",
      description: "Thông tin dịch vụ",
      description_en: "Service information",
      icon: "cluster",
      breadcrumbParentId: "/main/setting/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/setting/service/detail/moto-packing/setup-fee",
      name: "Gửi xe",
      name_en: "Motor parking",
      route: "/main/setting/service/detail/moto-packing/setup-fee",
      description: "Cài đặt phí",
      description_en: "Setup fee",
      icon: "cluster",
      breadcrumbParentId: "/main/setting/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/setting/service/detail/apartment-fee",
      name: "Quản lý toà nhà",
      name_en: "Building management",
      route: "/main/setting/service/detail/apartment-fee",
      description: "Thông tin dịch vụ",
      description_en: "Service information",
      icon: "cluster",
      breadcrumbParentId: "/main/setting/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/setting/service/detail/apartment-fee/infomation",
      name: "Quản lý toà nhà",
      name_en: "Building management",
      route: "/main/setting/service/detail/apartment-fee/infomation",
      description: "Thông tin dịch vụ",
      description_en: "Service information",
      icon: "cluster",
      breadcrumbParentId: "/main/setting/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/setting/service/detail/utility-free",
      name: "Tiện ích",
      name_en: "Amenity",
      route: "/main/setting/service/detail/utility-free",
      description: "Thông tin dịch vụ",
      description_en: "Service information",
      icon: "cluster",
      breadcrumbParentId: "/main/setting/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/setting/service/detail/utility-free/infomation",
      name: "Tiện ích",
      name_en: "Amenity",
      route: "/main/setting/service/detail/utility-free/infomation",
      description: "Thông tin dịch vụ",
      description_en: "Service information",
      icon: "cluster",
      breadcrumbParentId: "/main/setting/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/setting/service/detail/utility-free/list",
      name: "Danh sách",
      name_en: "List",
      route: "/main/setting/service/detail/utility-free/list",
      description: "Danh sách tiện ích",
      description_en: "Amenity list",
      icon: "cluster",
      breadcrumbParentId: "/main/setting/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/setting/service/detail/utility-free/add",
      name: "Dịch vụ",
      name_en: "Service",
      route: "/main/setting/service/detail/utility-free/add",
      description: "Thông tin dịch vụ",
      description_en: "Service information",
      icon: "cluster",
      breadcrumbParentId: "/main/setting/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/setting/service/detail/utility-free/edit/:id",
      name: "Dịch vụ",
      name_en: "Service",
      route: "/main/setting/service/detail/utility-free/edit/:id",
      description: "Thông tin dịch vụ",
      description_en: "Service information",
      icon: "cluster",
      breadcrumbParentId: "/main/setting/service/detail/generate",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/setting/service/detail/utility-free/detail/:id/info",
      name: "Dịch vụ",
      name_en: "Service",
      route: "/main/setting/service/detail/utility-free/detail/:id/info",
      description: "Thông tin dịch vụ",
      description_en: "Service information",
      icon: "cluster",
      breadcrumbParentId: "/main/setting/service/detail/utility-free/list",
      invisibleInMenu: true,
      denied: true,
    },
    {
      id: "/main/setting/service/detail/utility-free/detail/:id/config",
      name: "Dịch vụ",
      name_en: "Service",
      route: "/main/setting/service/detail/utility-free/detail/:id/config",
      description: "Thông tin dịch vụ",
      description_en: "Service information",
      icon: "cluster",
      breadcrumbParentId: "/main/setting/service/detail/utility-free/list",
      invisibleInMenu: true,
      denied: true,
    },
    //===================End=========================

    {
      id: "/main/setting/handbook",
      name: "Sổ tay cư dân",
      name_en: "Resident handbook",
      route: "/main/setting/handbook",
      description: "Sổ tay cư dân",
      description_en: "Resident handbook",
      icon: "book",
      breadcrumbParentId: "/main/setting",
      menuParentId: "/main/setting",
      denied: true,
    },

    {
      id: "/main/setting/logs",
      name: "Lịch sử người dùng",
      name_en: "User history",
      description: "Lịch sử người dùng",
      description_en: "User history",
      route: "/main/setting/logs",
      icon: "user",
      breadcrumbParentId: "/main/setting",
      menuParentId: "/main/setting",
      denied: true,
    },
    {
      id: "/main/setting/resources",
      name: "Tài nguyên",
      name_en: "Resources",
      description: "Tài nguyên hệ thống",
      description_en: "System resources",
      route: "/main/setting/resources",
      icon: "database",
      breadcrumbParentId: "/main/setting",
      menuParentId: "/main/setting",
      denied: true,
    },
    {
      id: "/main/setting/resources/email",
      name: "Email",
      description: "Tài nguyên hệ thống",
      description_en: "System resources",
      route: "/main/setting/resources/email",
      icon: "user",
      breadcrumbParentId: "/main/setting/resources",
      denied: true,
      invisibleInMenu: true,
    },
    {
      id: "/main/setting/resources/notification",
      name: "Notification",
      description: "Tài nguyên hệ thống",
      description_en: "System resources",
      route: "/main/setting/resources/notification",
      icon: "user",
      breadcrumbParentId: "/main/setting/resources",
      denied: true,
      invisibleInMenu: true,
    },
    // {
    //   id: "/main/setting/resources/sms",
    //   name: "SMS",
    //   description: "Tài nguyên hệ thống",
    //   description_en: "System resources",
    //   route: "/main/setting/resources/sms",
    //   icon: "user",
    //   breadcrumbParentId: "/main/setting/resources",
    //   denied: true,
    //   invisibleInMenu: true,
    // },
    {
      id: "/main/account/settings/base",
      name: "Cá nhân / Thông tin",
      name_en: "Profile / Information",
      description: "Cài đặt thông tin cơ bản",
      description_en: "Set up basic information ",
      icon: "info-circle",
      route: "/main/account/settings/base",
      breadcrumbParentId: "/main",
      main: true,
      invisibleInMenu: true,
    },
    {
      id: "/main/account/settings/security",
      name: "Cá nhân",
      name_en: "Profile",
      description: "Cài đặt bảo mật",
      description_en: "Security setting",
      icon: "security-scan",
      route: "/main/account/settings/security",
      breadcrumbParentId: "/main",
      main: true,
      invisibleInMenu: true,
    },
    {
      id: "/main/account/settings/changepassword",
      name: "Cá nhân / Mật khẩu",
      name_en: "Profile / Password",
      description: "Đổi mật khẩu",
      description_en: "Change password",
      icon: "security-scan",
      route: "/main/account/settings/changepassword",
      breadcrumbParentId: "/main",
      main: true,
      invisibleInMenu: true,
    },
    {
      id: "/main/setting/notification-fee-manager",
      name: "Mẫu bản tin",
      name_en: "News templates",
      description: "Quản lý mẫu bản tin",
      description_en: "News templates management",
      route: "/main/setting/notification-fee-manager",
      breadcrumbParentId: "/main/setting",
      menuParentId: "/main/setting",
      icon: "snippets",
      denied: true,
    },

    {
      id: "/main/service/cloud",
      name: "Khởi tạo dịch vụ",
      name_en: "Service activation",
      route: "/main/service/cloud",
      description: "Danh sách dịch vụ",
      description_en: "List of services",
      icon: "cloud-server",
      denied: true,
    },
    {
      id: "/main/service/add/:id",
      name: "Thêm dịch vụ",
      name_en: "Add service",
      route: "/main/service/add/:id",
      description: "Thêm dịch vụ",
      description_en: "Add service",
      icon: "cloud-server",
      breadcrumbParentId: "/main/service/cloud",
      invisibleInMenu: true,
      denied: true,
    },
  ],

  /* I18n configuration, `languages` and `defaultLanguage` are required currently. */
  // i18n: {
  //   /* Countrys flags: https://www.flaticon.com/packs/countrys-flags */
  //   languages: [
  //     {
  //       key: 'pt-br',
  //       title: 'Português',
  //       flag: '/brazil.svg',
  //     },
  //     {
  //       key: 'en',
  //       title: 'English',
  //       flag: '/america.svg',
  //     },
  //     {
  //       key: 'zh',
  //       title: '中文',
  //       flag: '/china.svg',
  //     },
  //   ],
  //   defaultLanguage: 'en',
  // },
};
