const ROUTER_MENU = [
  {
    id: "/main/home",
    name: "Trang chủ",
    description: "Trang chủ",
    route: "/main/home",
    icon: "home",
    main: true,
  },
  {
    id: "/main/notification",
    name: "Thông báo",
    route: "/main/notification",
    description: "Thông báo",
    icon: "reconciliation",
    denied: true,
    children: [
      {
        id: "/main/notification/list",
        name: "Danh sách",
        route: "/main/notification/list",
        description: "Danh sách thông báo",
        icon: "unordered-list",
        breadcrumbParentId: "/main/notification",
        menuParentId: "/main/notification",
        denied: true,
      },
      {
        id: "/main/notification/add/:id",
        name: "Tạo thông báo",
        route: "/main/notification/add/:id",
        description: "Tạo thông báo mới",
        icon: "file-add",
        breadcrumbParentId: "/main/notification",
        menuParentId: "/main/notification",
        denied: true,
      },
      {
        id: "/main/notification/category",
        name: "Danh mục",
        route: "/main/notification/category",
        description: "Danh mục thông báo",
        icon: "tags",
        breadcrumbParentId: "/main/notification",
        menuParentId: "/main/notification",
        denied: true,
      },
      {
        id: "/main/notification/detail/:id",
        name: "Chi tiết",
        route: "/main/notification/detail/:id",
        description: "Chi tiết bản tin",
        icon: "tags",
        breadcrumbParentId: "/main/notification/list",
        menuParentId: "/main/notification",
        invisibleInMenu: true,
        denied: true,
      },
    ],
  },
  {
    id: "/main/ticket",
    name: "Yêu cầu",
    route: "/main/ticket",
    description: "Yêu cầu",
    icon: "message",
    denied: true,
    children: [
      {
        id: "/main/ticket/list",
        name: "Danh sách",
        route: "/main/ticket/list",
        description: "Danh sách yêu cầu",
        icon: "unordered-list",
        breadcrumbParentId: "/main/ticket",
        menuParentId: "/main/ticket",
        denied: true,
      },
      {
        id: "/main/ticket/category",
        name: "Danh mục",
        route: "/main/ticket/category",
        description: "Danh sách danh mục",
        icon: "tags",
        breadcrumbParentId: "/main/ticket",
        menuParentId: "/main/ticket",
        denied: true,
      },
      {
        id: "/main/ticket/detail/:id",
        name: "Chi tiết",
        route: "/main/ticket/detail/:id",
        description: "Chi tiết phản ánh",
        icon: "tags",
        breadcrumbParentId: "/main/ticket/list",
        invisibleInMenu: true,
        denied: true,
      },
    ],
  },
  {
    id: "/main/service",
    name: "Dịch vụ",
    route: "/main/service",
    description: "Yêu cầu",
    icon: "reconciliation",
    // denied: true,
    main: true,
    children: [
      {
        id: "/main/service/list",
        name: "Dịch vụ cung cấp",
        route: "/main/service/list",
        description: "Danh sách dịch vụ cung cấp",
        icon: "unordered-list",
        breadcrumbParentId: "/main/service",
        menuParentId: "/main/service",
        // denied: true,
        main: true,
        children: [
          {
            id: "/main/service/detail/water",
            name: "Chi tiết",
            route: "/main/service/detail/water",
            description: "Dịch vụ nước",
            icon: "unordered-list",
            breadcrumbParentId: "/main/service/list",
            invisibleInMenu: true,
            // denied: true,
            main: true,
          },
          {
            id: "/main/service/detail/water/infomation",
            name: "Chi tiết",
            route: "/main/service/detail/water/infomation",
            description: "Dịch vụ nước",
            icon: "unordered-list",
            breadcrumbParentId: "/main/service/list",
            invisibleInMenu: true,
            // denied: true,
            main: true,
          },
          {
            id: "/main/service/detail/water/payment",
            name: "Chi tiết",
            route: "/main/service/detail/water/payment",
            description: "Dịch vụ nước",
            icon: "unordered-list",
            breadcrumbParentId: "/main/service/list",
            invisibleInMenu: true,
            // denied: true,
            main: true,
          },
        ],
      },
      {
        id: "/main/service/cloud",
        name: "Cloud",
        route: "/main/service/cloud",
        description: "Danh sách dịch vụ Cloud",
        icon: "cloud-server",
        breadcrumbParentId: "/main/service",
        menuParentId: "/main/service",
        // denied: true,
        main: true,
      },
      {
        id: "/main/service/add/:id",
        name: "Thêm dịch vụ",
        route: "/main/service/add/:id",
        description: "Thêm dịch vụ",
        icon: "cloud-server",
        breadcrumbParentId: "/main/service/cloud",
        invisibleInMenu: true,
        // denied: true,
        main: true,
      },
      {
        id: "/main/service/providers",
        name: "Nhà cung cấp",
        route: "/main/service/providers",
        description: "Danh sách nhà cung cấp dịch vụ",
        icon: "solution",
        breadcrumbParentId: "/main/service",
        menuParentId: "/main/service",
        // denied: true,
        main: true,
      },
      {
        id: "/main/service/providers/add",
        name: "Thêm mới",
        route: "/main/service/providers/add",
        description: "Thêm mới nhà cung cấp dịch vụ",
        icon: "unordered-list",
        breadcrumbParentId: "/main/service/providers",
        invisibleInMenu: true,
        // denied: true,
        main: true,
      },
      {
        id: "/main/service/providers/detail/:id",
        name: "Chi tiết",
        route: "/main/service/providers/detail/:id",
        description: "Chi tiết nhà cung cấp dịch vụ",
        icon: "unordered-list",
        breadcrumbParentId: "/main/service/providers",
        invisibleInMenu: true,
        // denied: true,
        main: true,
      },
    ],
  },
  {
    id: "/main/finance",
    name: "Tài chính",
    route: "/main/finance",
    description: "Quản lý tài chính",
    icon: "bank",
    // denied: true,
    main: true,
    children: [
      {
        id: "/main/finance/fees",
        name: "Quản lý thu phí",
        route: "/main/finance/fees",
        description: "Quản lý thu phí",
        icon: "euro",
        breadcrumbParentId: "/main/finance",
        menuParentId: "/main/finance",
        // denied: true,
        main: true,
      },
      {
        id: "/main/finance/bill/Add",
        name: "Tạo phiếu thu",
        route: "/main/finance/bill/Add",
        description: "Tạo phiếu thu dịch vụ",
        icon: "euro",
        breadcrumbParentId: "/main/finance/fees",
        invisibleInMenu: true,
        // denied: true,
        main: true,
      },
      {
        id: "/main/finance/bills",
        name: "Phiếu thanh toán",
        route: "/main/finance/bills",
        description: "Danh sách phiếu thu",
        icon: "transaction",
        breadcrumbParentId: "/main/finance",
        menuParentId: "/main/finance",
        // denied: true,
        main: true,
      },
      {
        id: "/main/finance/bills/detail/:id",
        name: "Phiếu thu",
        route: "/main/finance/bills/detail/:id",
        description: "Chi tiết phiếu thu",
        icon: "euro",
        breadcrumbParentId: "/main/finance/bills",
        invisibleInMenu: true,
        // denied: true,
        main: true,
      },
    ],
  },
  {
    id: "/main/resident",
    name: "Cư dân",
    route: "/main/resident",
    description: "Trang chủ",
    icon: "user",
    denied: true,
    children: [
      {
        id: "/main/resident/list",
        name: "Danh sách",
        description: "Danh sách cư dân",
        icon: "unordered-list",
        route: "/main/resident/list",
        breadcrumbParentId: "/main/resident",
        menuParentId: "/main/resident",
        denied: true,
      },
      {
        id: "/main/resident/add",
        name: "Thêm mới",
        description: "Thêm mới cư dân",
        icon: "user-add",
        route: "/main/resident/add",
        breadcrumbParentId: "/main/resident",
        menuParentId: "/main/resident",
        denied: true,
      },
      {
        id: "/main/resident/detail/:id",
        name: "Chi tiết cư dân",
        description: "Chi tiết thông tin cư dân",
        route: "/main/resident/detail/:id",
        breadcrumbParentId: "/main/resident/list",
        invisibleInMenu: true,
        denied: true,
      },
    ],
  },
  {
    id: "/main/staff",
    name: "Nhân sự",
    route: "/main/staff",
    description: "Trang chủ",
    icon: "contacts",
    denied: true,
    children: [
      {
        id: "/main/staff/list",
        name: "Danh sách",
        description: "Danh sách nhân sự",
        icon: "unordered-list",
        route: "/main/staff/list",
        breadcrumbParentId: "/main/staff",
        menuParentId: "/main/staff",
        denied: true,
      },
      {
        id: "/main/staff/add",
        name: "Thêm mới",
        description: "Thêm mới nhân sự",
        icon: "user-add",
        route: "/main/staff/add",
        breadcrumbParentId: "/main/staff",
        menuParentId: "/main/staff",
        denied: true,
      },
      {
        id: "/main/staff/edit/:id",
        name: "Cập nhật",
        description: "Chỉnh sửa thông tin nhân sự",
        route: "/main/staff/edit/:id",
        breadcrumbParentId: "/main/staff/list",
        invisibleInMenu: true,
        denied: true,
      },
    ],
  },
  {
    id: "/main/setting",
    name: "Cấu hình",
    route: "/main/setting",
    icon: "tool",
    children: [
      {
        id: "/main/setting/infomation",
        name: "Thông tin",
        description: "Thông tin cụm ",
        route: "/main/setting/infomation",
        breadcrumbParentId: "/main/setting",
        menuParentId: "/main/setting",
        icon: "home",
        // denied: true,
        main: true,
        // denied: true,
        // invisibleInMenu: true
      },
      {
        id: "/main/setting/plane",
        name: "Mặt bằng",
        description: "Cấu hình mặt bằng",
        route: "/main/setting/plane",
        breadcrumbParentId: "/main/setting",
        menuParentId: "/main/setting",
        icon: "cluster",
        denied: true,
      },
      {
        id: "/main/setting/apartment",
        name: "Bất động sản",
        description: "Danh sách bất động sản",
        route: "/main/setting/apartment",
        breadcrumbParentId: "/main/setting",
        menuParentId: "/main/setting",
        icon: "shop",
        denied: true,
      },
      {
        id: "/main/setting/apartment/add",
        name: "Thêm mới",
        description: "Thêm mới bất động sản",
        route: "/main/setting/apartment/add",
        breadcrumbParentId: "/main/setting/apartment",
        invisibleInMenu: true,
        denied: true,
        // invisibleInMenu: true
      },
      {
        id: "/main/setting/apartment/detail/:id",
        name: "Chi tiết",
        description: "Chi tiết bất động sản",
        route: "/main/setting/apartment/detail/:id",
        breadcrumbParentId: "/main/setting/apartment",
        invisibleInMenu: true,
        denied: true,
        // invisibleInMenu: true
      },
      {
        id: "/main/setting/roles",
        name: "Tổ chức nhân sự",
        description: "Danh sách nhóm quyền",
        route: "/main/setting/roles",
        icon: "user",
        breadcrumbParentId: "/main/setting",
        menuParentId: "/main/setting",
        denied: true,
      },
      {
        id: "/main/setting/roles/create",
        name: "Thêm mới nhóm quyền",
        description: "Thêm mới nhóm quyền",
        route: "/main/setting/roles/create",
        icon: "user",
        breadcrumbParentId: "/main/setting/roles",
        invisibleInMenu: true,
        denied: true,
      },
      {
        id: "/main/setting/roles/edit/:id",
        name: "Chỉnh sửa nhóm quyền",
        description: "Chỉnh sửa nhóm quyền",
        route: "/main/setting/roles/edit/:id",
        icon: "user",
        breadcrumbParentId: "/main/setting/roles",
        invisibleInMenu: true,
        denied: true,
      },
    ],
  },
  {
    id: "/main/account/settings",
    name: "Cá nhân",
    route: "/main/account/settings",
    description: "Cá nhân",
    icon: "setting",
    main: true,
    children: [
      {
        id: "/main/account/settings/base",
        name: "Cơ bản",
        description: "Cài đặt thông tin cơ bản",
        icon: "info-circle",
        route: "/main/account/settings/base",
        breadcrumbParentId: "/main/account/settings",
        menuParentId: "/main/account/settings",
        main: true,
      },
      {
        id: "/main/account/settings/security",
        name: "Bảo mật",
        description: "Cài đặt bảo mật",
        icon: "security-scan",
        route: "/main/account/settings/security",
        breadcrumbParentId: "/main/account/settings",
        menuParentId: "/main/account/settings",
        main: true,
      },
    ],
  },
  // {
  //   id: "/main/merge-card",
  //   name: "Thẻ hợp nhất",
  //   route: "/main/merge-card",
  //   description: "Thẻ hợp nhất",
  //   icon: "idcard",
  //   denied: true,
  //   children: [
  //     {
  //       id: "/main/merge-card/list",
  //       name: "Danh sách",
  //       description: "Danh sách thẻ hợp nhất",
  //       icon: "unordered-list",
  //       route: "/main/merge-card/list",
  //       breadcrumbParentId: "/main/merge-card",
  //       menuParentId: "/main/merge-card",
  //       denied: true,
  //     },
  //     {
  //       id: "/main/merge-card/detail/:id",
  //       name: "Chi tiết thẻ",
  //       description: "Chi tiết thông tin thẻ",
  //       route: "/main/merge-card/detail/:id",
  //       breadcrumbParentId: "/main/merge-card/list",
  //       icon: "tags",
  //       invisibleInMenu: true,
  //       denied: true,
  //     },
  //   ],
  // },
];

module.exports = function () {
  let routers = [];

  const loopChildren = (root, lst) => {
    const { children, ...rest } = root;
    lst.push(rest);
    if (children) {
      children.forEach((element) => {
        loopChildren(element, lst);
      });
    }
  };

  ROUTER_MENU.forEach((element) => {
    loopChildren(element, routers);
  });
  return routers;
};
