/*
 *
 * Config Send constants
 *
 */

export const DEFAULT_ACTION = 'app/Sends/DEFAULT_ACTION';

export const FETCH_ALL_NOTIFY_SEND_CONFIG = 'app/Sends/FETCH_ALL_NOTIFY_SEND_CONFIG';
export const FETCH_ALL_NOTIFY_SEND_CONFIG_COMPLETE = 'app/Sends/FETCH_ALL_NOTIFY_SEND_CONFIG_COMPLETE';

export const UPDATE_NOTIFY_SEND_CONFIG = 'app/Sends/UPDATE_NOTIFY_SEND_CONFIG';
export const UPDATE_NOTIFY_SEND_CONFIG_COMPLETE = 'app/Sends/UPDATE_NOTIFY_SEND_CONFIG_COMPLETE';

export const UPDATE_ALL_NOTIFY_SEND_CONFIG = 'app/Sends/UPDATE_ALL_NOTIFY_SEND_CONFIG';
export const UPDATE_ALL_NOTIFY_SEND_CONFIG_COMPLETE = 'app/Sends/UPDATE_ALL_NOTIFY_SEND_CONFIG_COMPLETE';


