/*
 *
 * NotificationUpdate constants
 *
 */

export const DEFAULT_ACTION = "app/NotificationUpdate/DEFAULT_ACTION";

export const FETCH_ALL_ANNOUNCEMENT_TEMPLATE_FEE =
  "app/NotificationAdd/FETCH_ALL_ANNOUNCEMENT_TEMPLATE_FEE";
export const FETCH_ALL_ANNOUNCEMENT_TEMPLATE_FEE_COMPLETE =
  "app/NotificationAdd/FETCH_ALL_ANNOUNCEMENT_TEMPLATE_FEE_COMPLETE";

export const FETCH_APARTMENT_FEE_REMINDER =
  "app/NotificationUpdate/FETCH_APARTMENT_FEE_REMINDER";
export const FETCH_APARTMENT_FEE_REMINDER_COMPLETE =
  "app/NotificationUpdate/FETCH_APARTMENT_FEE_REMINDER_COMPLETE";

export const FETCH_ANNOUNCEMENT_TEMPLATE_FEE =
  "app/NotificationUpdate/FETCH_ANNOUNCEMENT_TEMPLATE_FEE";
export const FETCH_ANNOUNCEMENT_TEMPLATE_FEE_COMPLETE =
  "app/NotificationUpdate/FETCH_ANNOUNCEMENT_TEMPLATE_FEE_COMPLETE";

export const CREATE_NOTIFICATION_FEE_REMINDER =
  "app/NotificationUpdate/CREATE_NOTIFICATION_FEE_REMINDER";
export const CREATE_NOTIFICATION_FEE_REMINDER_COMPLETE =
  "app/NotificationUpdate/CREATE_NOTIFICATION_FEE_REMINDER_COMPLETE";

export const FETCH_CATEGORY = "app/NotificationUpdate/FETCH_CATEGORY";
export const FETCH_CATEGORY_COMPLETE =
  "app/NotificationUpdate/FETCH_CATEGORY_COMPLETE";

export const FETCH_BUILDING_AREA_ACTION =
  "app/NotificationUpdate/FETCH_BUILDING_AREA_ACTION";
export const FETCH_BUILDING_AREA_COMPLETE_ACTION =
  "app/NotificationUpdate/FETCH_BUILDING_AREA_COMPLETE_ACTION";

export const FETCH_APARTMENT_SENT =
  "app/NotificationUpdate/FETCH_APARTMENT_SENT";
export const FETCH_APARTMENT_SENT_COMPLETE =
  "app/NotificationUpdate/FETCH_APARTMENT_SENT_COMPLETE";

export const FETCH_DETAIL_ANNOUNCEMENT =
  "app/NotificationUpdate/FETCH_DETAIL_ANNOUNCEMENT";
export const FETCH_DETAIL_ANNOUNCEMENT_COMPLETE =
  "app/NotificationUpdate/FETCH_DETAIL_ANNOUNCEMENT_COMPLETE";

export const UPDATE_NOTIFICATION_ACTION =
  "app/NotificationUpdate/UPDATE_NOTIFICATION_ACTION";
export const UPDATE_NOTIFICATION_COMPLETE_ACTION =
  "app/NotificationUpdate/UPDATE_NOTIFICATION_COMPLETE_ACTION";
