<?php

return[
    [
        "id"           => 1,
        "name"         => 'Phạm Văn Hưởng',
        "domain"       => 'domainActive',
        "email"        => 'phamvanhuong.hd@gmail.com',
        "phone"        => '0868605579',
        "password"     => '$2y$13$Wz84Hmn32fditjLURoifZOtOGWVkxg89F/CtvWX0fIZm2MHpRkYj.', //123456
        "auth_key"     => '',
        "status"       => 0, // '0 : khởi tạo , 1: được active, 2 : bị khóa',
        "user_id"      => 1,
        "is_deleted"   => 0, //'0: not delete; 1: is deleted',
        "deleted_at"   => null,
        "verify_email" => 0, // '0: inactive; 1: active',
        "verify_phone" => 0, // '0: inactive; 1: active',
        "created_at"   => time(),
        "updated_at"   => time(),
    ],
    [
        "id"           => 2,
        "name"         => 'Phạm Văn Hưởng',
        "domain"       => 'domainBan',
        "email"        => 'a@gmail.com',
        "phone"        => '0868605579',
        "password"     => '$2y$13$Wz84Hmn32fditjLURoifZOtOGWVkxg89F/CtvWX0fIZm2MHpRkYj.', //123456
        "auth_key"     => '',
        "status"       => 2, // '0 : khởi tạo , 1: được active, 2 : bị khóa',
        "user_id"      => 1,
        "is_deleted"   => 0, //'0: not delete; 1: is deleted',
        "deleted_at"   => null,
        "verify_email" => 0, // '0: inactive; 1: active',
        "verify_phone" => 0, // '0: inactive; 1: active',
        "created_at"   => time(),
        "updated_at"   => time(),
    ],
    [
        "id"           => 3,
        "name"         => 'Phạm Văn Hưởng',
        "domain"       => 'domainDeleted',
        "email"        => 'b@gmail.com',
        "phone"        => '0868605579',
        "password"     => '$2y$13$Wz84Hmn32fditjLURoifZOtOGWVkxg89F/CtvWX0fIZm2MHpRkYj.', //123456
        "auth_key"     => '',
        "status"       => 1, // '0 : khởi tạo , 1: được active, 2 : bị khóa',
        "user_id"      => 1,
        "is_deleted"   => 1, //'0: not delete; 1: is deleted',
        "deleted_at"   => null,
        "verify_email" => 0, // '0: inactive; 1: active',
        "verify_phone" => 0, // '0: inactive; 1: active',
        "created_at"   => time(),
        "updated_at"   => time(),
    ],
    [
        "id"           => 4,
        "name"         => 'Phạm Văn Hưởng',
        "domain"       => 'domainActiveOther',
        "email"        => 'phamvanhuong.it@gmail.com',
        "phone"        => '0868605579',
        "password"     => '$2y$13$Wz84Hmn32fditjLURoifZOtOGWVkxg89F/CtvWX0fIZm2MHpRkYj.', //123456
        "auth_key"     => '',
        "status"       => 0, // '0 : khởi tạo , 1: được active, 2 : bị khóa',
        "user_id"      => 1,
        "is_deleted"   => 0, //'0: not delete; 1: is deleted',
        "deleted_at"   => null,
        "verify_email" => 0, // '0: inactive; 1: active',
        "verify_phone" => 0, // '0: inactive; 1: active',
        "created_at"   => time(),
        "updated_at"   => time(),
    ],
];
