/*
 *
 * NotificationUpdate constants
 *
 */

export const DEFAULT_ACTION = "app/NotificationUpdate/DEFAULT_ACTION";


export const FETCH_ULTILITY_ACTION = "app/NotificationUpdate/FETCH_ULTILITY_ACTION";


export const FETCH_CATEGORY_ACTION = "app/NotificationUpdate/FETCH_CATEGORY_ACTION";
export const FETCH_CATEGORY_COMPLETE_ACTION = "app/NotificationUpdate/FETCH_CATEGORY_COMPLETE_ACTION";

export const FETCH_BUILDING_AREA_ACTION = "app/NotificationUpdate/FETCH_BUILDING_AREA_ACTION";
export const FETCH_BUILDING_AREA_COMPLETE_ACTION = "app/NotificationUpdate/FETCH_BUILDING_AREA_COMPLETE_ACTION";

export const CREATE_NOTIFICATION_ACTION = "app/NotificationUpdate/CREATE_NOTIFICATION_ACTION";
export const CREATE_NOTIFICATION_COMPLETE_ACTION = "app/NotificationUpdate/CREATE_NOTIFICATION_COMPLETE_ACTION";

export const UPDATE_NOTIFICATION_ACTION = "app/NotificationUpdate/UPDATE_NOTIFICATION_ACTION";
export const UPDATE_NOTIFICATION_COMPLETE_ACTION = "app/NotificationUpdate/UPDATE_NOTIFICATION_COMPLETE_ACTION";

export const FETCH_TOTAL_APARTMENT_ACTION = "app/NotificationUpdate/FETCH_TOTAL_APARTMENT_ACTION";
export const FETCH_TOTAL_APARTMENT_COMPLETE_ACTION = "app/NotificationUpdate/FETCH_TOTAL_APARTMENT_COMPLETE_ACTION";

export const FETCH_DETAIL_NOTIFICATION = "app/NotificationUpdate/FETCH_DETAIL_NOTIFICATION";
export const FETCH_DETAIL_NOTIFICATION_COMPLETE = "app/NotificationUpdate/FETCH_DETAIL_NOTIFICATION_COMPLETE";
