/*
 *
 * ApartmentAdd constants
 *
 */

export const DEFAULT_ACTION = "app/ApartmentAdd/DEFAULT_ACTION";
export const FETCH_BUILDING_AREA = "app/ApartmentAdd/FETCH_BUILDING_AREA";
export const FETCH_BUILDING_AREA_COMPLETE = "app/ApartmentAdd/FETCH_BUILDING_AREA_COMPLETE";

export const CREATE_APARTMENT = "app/ApartmentAdd/CREATE_APARTMENT";
export const CREATE_APARTMENT_COMPLETE = "app/ApartmentAdd/CREATE_APARTMENT_COMPLETE";

export const FETCH_DETAIL_APARTMENT = "app/ApartmentAdd/FETCH_DETAIL_APARTMENT";
export const FETCH_DETAIL_APARTMENT_COMPLETE = "app/ApartmentAdd/FETCH_DETAIL_APARTMENT_COMPLETE";

export const FETCH_ALL_APARTMENT_TYPE = "app/ApartmentAdd/FETCH_ALL_APARTMENT_TYPE";
export const FETCH_ALL_APARTMENT_TYPE_COMPLETE = "app/ApartmentAdd/FETCH_ALL_APARTMENT_TYPE_COMPLETE";

export const FETCH_ALL_RESIDENT_BY_PHONE = "app/ApartmentAdd/FETCH_ALL_RESIDENT_BY_PHONE";
export const FETCH_ALL_RESIDENT_BY_PHONE_COMPLETE = "app/ApartmentAdd/FETCH_ALL_RESIDENT_BY_PHONE_COMPLETE";
