/*
 *
 * NotificationFeeUpdate constants
 *
 */

export const DEFAULT_ACTION = "app/NotificationFeeUpdate/DEFAULT_ACTION";


export const FETCH_APARTMENT_FEE_REMINDER = "app/NotificationFeeUpdate/FETCH_APARTMENT_FEE_REMINDER";
export const FETCH_APARTMENT_FEE_REMINDER_COMPLETE = "app/NotificationFeeUpdate/FETCH_APARTMENT_FEE_REMINDER_COMPLETE";

export const FETCH_ANNOUNCEMENT_TEMPLATE_FEE = "app/NotificationFeeUpdate/FETCH_ANNOUNCEMENT_TEMPLATE_FEE";
export const FETCH_ANNOUNCEMENT_TEMPLATE_FEE_COMPLETE = "app/NotificationFeeUpdate/FETCH_ANNOUNCEMENT_TEMPLATE_FEE_COMPLETE";

export const CREATE_NOTIFICATION_FEE_REMINDER = "app/NotificationFeeUpdate/CREATE_NOTIFICATION_FEE_REMINDER";
export const CREATE_NOTIFICATION_FEE_REMINDER_COMPLETE = "app/NotificationFeeUpdate/CREATE_NOTIFICATION_FEE_REMINDER_COMPLETE";

export const FETCH_CATEGORY = "app/NotificationFeeUpdate/FETCH_CATEGORY";
export const FETCH_CATEGORY_COMPLETE = "app/NotificationFeeUpdate/FETCH_CATEGORY_COMPLETE";

export const FETCH_BUILDING_AREA_ACTION = "app/NotificationFeeUpdate/FETCH_BUILDING_AREA_ACTION";
export const FETCH_BUILDING_AREA_COMPLETE_ACTION = "app/NotificationFeeUpdate/FETCH_BUILDING_AREA_COMPLETE_ACTION";

export const FETCH_APARTMENT_SENT = "app/NotificationFeeUpdate/FETCH_APARTMENT_SENT";
export const FETCH_APARTMENT_SENT_COMPLETE = "app/NotificationFeeUpdate/FETCH_APARTMENT_SENT_COMPLETE";

export const FETCH_DETAIL_ANNOUNCEMENT = "app/NotificationFeeUpdate/FETCH_DETAIL_ANNOUNCEMENT";
export const FETCH_DETAIL_ANNOUNCEMENT_COMPLETE = "app/NotificationFeeUpdate/FETCH_DETAIL_ANNOUNCEMENT_COMPLETE";

export const UPDATE_NOTIFICATION_ACTION = "app/NotificationFeeUpdate/UPDATE_NOTIFICATION_ACTION";
export const UPDATE_NOTIFICATION_COMPLETE_ACTION = "app/NotificationFeeUpdate/UPDATE_NOTIFICATION_COMPLETE_ACTION";
