/*
 *
 * NotificationDetail constants
 *
 */

export const DEFAULT_ACTION = "app/NotificationDetail/DEFAULT_ACTION";

export const FETCH_NOTIFICATION_DETAIL =
  "app/NotificationDetail/FETCH_NOTIFICATION_DETAIL";
export const FETCH_NOTIFICATION_DETAIL_COMPLETE =
  "app/NotificationDetail/FETCH_NOTIFICATION_DETAIL_COMPLETE";

export const FETCH_APARTMENT_FEE_REMINDER =
  "app/NotificationDetail/FETCH_APARTMENT_FEE_REMINDER";
export const FETCH_APARTMENT_FEE_REMINDER_COMPLETE =
  "app/NotificationDetail/FETCH_APARTMENT_FEE_REMINDER_COMPLETE";

export const FETCH_SURVEY_ANSWER = "app/NotificationDetail/FETCH_SURVEY_ANSWER";
export const FETCH_SURVEY_ANSWER_COMPLETE =
  "app/NotificationDetail/FETCH_SURVEY_ANSWER_COMPLETE";

export const FETCH_REPORT_CHART = "app/NotificationDetail/FETCH_REPORT_CHART";
export const FETCH_REPORT_CHART_COMPLETE =
  "app/NotificationDetail/FETCH_REPORT_CHART_COMPLETE";

export const FETCH_APARTMENT_SENT =
  "app/NotificationDetail/FETCH_APARTMENT_SENT";
export const FETCH_APARTMENT_SENT_COMPLETE =
  "app/NotificationDetail/FETCH_APARTMENT_SENT_COMPLETE";

export const FETCH_ANNOUNCEMENT_TEMPLATE_FEE =
  "app/NotificationDetail/FETCH_ANNOUNCEMENT_TEMPLATE_FEE";
export const FETCH_ANNOUNCEMENT_TEMPLATE_FEE_COMPLETE =
  "app/NotificationDetail/FETCH_ANNOUNCEMENT_TEMPLATE_FEE_COMPLETE";

export const CREATE_NOTIFICATION_FEE_REMINDER =
  "app/NotificationDetail/CREATE_NOTIFICATION_FEE_REMINDER";
export const CREATE_NOTIFICATION_FEE_REMINDER_COMPLETE =
  "app/NotificationDetail/CREATE_NOTIFICATION_FEE_REMINDER_COMPLETE";

export const FETCH_CATEGORY = "app/NotificationDetail/FETCH_CATEGORY";
export const FETCH_CATEGORY_COMPLETE =
  "app/NotificationDetail/FETCH_CATEGORY_COMPLETE";
