/*
 *
 * TicketDetail constants
 *
 */

export const DEFAULT_ACTION = "app/TicketDetail/DEFAULT_ACTION";

export const CHAT_BOX_TYPE_EXTERNAL = "app/TicketDetail/CHAT_BOX_TYPE_EXTERNAL";
export const CHAT_BOX_TYPE_INTERNAL = "app/TicketDetail/CHAT_BOX_TYPE_INTERNAL";

export const FETCH_TICKET_DETAIL = "app/TicketDetail/FETCH_TICKET_DETAIL";
export const FETCH_TICKET_DETAIL_COMPLETE =
  "app/TicketDetail/FETCH_TICKET_DETAIL_COMPLETE";

export const FETCH_EXTERNAL_MESSAGES =
  "app/TicketDetail/FETCH_EXTERNAL_MESSAGES";
export const FETCH_EXTERNAL_MESSAGES_COMPLETE =
  "app/TicketDetail/FETCH_EXTERNAL_MESSAGES_COMPLETE";

export const FETCH_INTERNAL_MESSAGES =
  "app/TicketDetail/FETCH_INTERNAL_MESSAGES";
export const FETCH_INTERNAL_MESSAGES_COMPLETE =
  "app/TicketDetail/FETCH_INTERNAL_MESSAGES_COMPLETE";

export const FETCH_MANAGERMENT_GROUPS =
  "app/TicketDetail/FETCH_MANAGERMENT_GROUPS";
export const FETCH_MANAGERMENT_GROUPS_COMPLETE =
  "app/TicketDetail/FETCH_MANAGERMENT_GROUPS_COMPLETE";

export const ADD_MANAGERMENT_GROUPS = "app/TicketDetail/ADD_MANAGERMENT_GROUPS";
export const ADD_MANAGERMENT_GROUPS_COMPLETE =
  "app/TicketDetail/ADD_MANAGERMENT_GROUPS_COMPLETE";

export const REMOVE_MANAGERMENT_GROUPS =
  "app/TicketDetail/REMOVE_MANAGERMENT_GROUPS";
export const REMOVE_MANAGERMENT_GROUPS_COMPLETE =
  "app/TicketDetail/REMOVE_MANAGERMENT_GROUPS_COMPLETE";

export const UPDATE_TICKET_STATUS = "app/TicketDetail/UPDATE_TICKET_STATUS";
export const UPDATE_TICKET_STATUS_COMPLETE =
  "app/TicketDetail/UPDATE_TICKET_STATUS_COMPLETE";

export const SEND_EXTERNAL_MESSAGE = "app/TicketDetail/SEND_EXTERNAL_MESSAGE";
export const SEND_EXTERNAL_MESSAGE_COMPLETE =
  "app/TicketDetail/SEND_EXTERNAL_MESSAGE_COMPLETE";

export const SEND_INTERNAL_MESSAGE = "app/TicketDetail/SEND_INTERNAL_MESSAGE";
export const SEND_INTERNAL_MESSAGE_COMPLETE =
  "app/TicketDetail/SEND_INTERNAL_MESSAGE_COMPLETE";

export const FETCH_AUTH_GROUP = "app/TicketDetail/FETCH_AUTH_GROUP";
export const FETCH_AUTH_GROUP_COMPLETE =
  "app/TicketDetail/FETCH_AUTH_GROUP_COMPLETE";

export const FETCH_CATEGORY = "app/TicketDetail/FETCH_CATEGORY";
export const FETCH_CATEGORY_COMPLETE =
  "app/TicketDetail/FETCH_CATEGORY_COMPLETE";
