/*
 *
 * NotificationList constants
 *
 */

export const DEFAULT_ACTION = "app/NotificationList/DEFAULT_ACTION";

export const FETCH_ALL_NOTIFICATIOIN_ACTION =
  "app/NotificationList/FETCH_ALL_NOTIFICATIOIN_ACTION";
export const FETCH_ALL_NOTIFICATIOIN_COMPLETE_ACTION =
  "app/NotificationList/FETCH_ALL_NOTIFICATIOIN_COMPLETE_ACTION";

export const FETCH_NOTIFICATION_CATEGORY_ACTION =
  "app/NotificationList/FETCH_NOTIFICATION_CATEGORY_ACTION";
export const FETCH_NOTIFICATION_CATEGORY_COMPLETE =
  "app/NotificationList/FETCH_NOTIFICATION_CATEGORY_COMPLETE";

export const DELETE_NOTIFICATION_ACTION =
  "app/NotificationList/DELETE_NOTIFICATION_ACTION";
export const DELETE_NOTIFICATION_COMPLETE_ACTION =
  "app/NotificationList/DELETE_NOTIFICATION_COMPLETE_ACTION";
