export const DEFAULT_ACTION = "app/RevenueByMonth/DEFAULT_ACTION";


export const FETCH_REVENUE_BY_MONTH_ACTION = "app/RevenueByMonth/FETCH_REVENUE_BY_MONTH_ACTION";
export const FETCH_REVENUE_BY_MONTH_COMPLETE_ACTION = "app/RevenueByMonth/FETCH_REVENUE_BY_MONTH_COMPLETE_ACTION";

