/*
 *
 * NotificationFeeManager constants
 *
 */

export const DEFAULT_ACTION = "app/NotificationFeeManager/DEFAULT_ACTION";

export const FETCH_ALL_ANNOUNCEMENT_TEMPLATE_FEE = "app/NotificationFeeManager/FETCH_ALL_ANNOUNCEMENT_TEMPLATE_FEE";
export const FETCH_ALL_ANNOUNCEMENT_TEMPLATE_FEE_COMPLETE = "app/NotificationFeeManager/FETCH_ALL_ANNOUNCEMENT_TEMPLATE_FEE_COMPLETE";

export const FETCH_ANNOUNCEMENT_TEMPLATE_FEE = "app/NotificationFeeManager/FETCH_ANNOUNCEMENT_TEMPLATE_FEE";
export const FETCH_ANNOUNCEMENT_TEMPLATE_FEE_COMPLETE = "app/NotificationFeeManager/FETCH_ANNOUNCEMENT_TEMPLATE_FEE_COMPLETE";

export const CREATE_ANNOUNCEMENT_TEMPLATE_FEE = "app/NotificationFeeManager/CREATE_ANNOUNCEMENT_TEMPLATE_FEE";
export const CREATE_ANNOUNCEMENT_TEMPLATE_FEE_COMPLETE = "app/NotificationFeeManager/CREATE_ANNOUNCEMENT_TEMPLATE_FEE_COMPLETE";

export const UPDATE_ANNOUNCEMENT_TEMPLATE_FEE = "app/NotificationFeeManager/UPDATE_ANNOUNCEMENT_TEMPLATE_FEE";
export const UPDATE_ANNOUNCEMENT_TEMPLATE_FEE_COMPLETE = "app/NotificationFeeManager/UPDATE_ANNOUNCEMENT_TEMPLATE_FEE_COMPLETE";

export const SHOW_CHOOSE_TEMPLATE_LIST = "app/NotificationFeeManager/SHOW_CHOOSE_TEMPLATE_LIST";
export const CHOOSE_CREATE_TEMPLATE = "app/NotificationFeeManager/CHOOSE_CREATE_TEMPLATE";

export const DELETE_ANNOUNCEMENT_TEMPLATE_FEE = "app/NotificationFeeManager/DELETE_ANNOUNCEMENT_TEMPLATE_FEE";
export const DELETE_ANNOUNCEMENT_TEMPLATE_FEE_COMPLETE = "app/NotificationFeeManager/DELETE_ANNOUNCEMENT_TEMPLATE_FEE_COMPLETE";