/*
 *
 * MaintainList constants
 *
 */

export const DEFAULT_ACTION = "app/MaintainList/DEFAULT_ACTION";

export const FETCH_ALL_MAINTAIN_DEVICES =
  "app/MaintainList/FETCH_ALL_MAINTAIN_DEVICES";
export const FETCH_ALL_MAINTAIN_DEVICES_COMPLETE =
  "app/MaintainList/FETCH_ALL_MAINTAIN_DEVICES_COMPLETE";

export const DELETE_MAINTAIN_DEVICES =
  "app/MaintainList/DELETE_MAINTAIN_DEVICES";
export const DELETE_MAINTAIN_DEVICES_COMPLETE =
  "app/MaintainList/DELETE_MAINTAIN_DEVICES_COMPLETE";

export const UPDATE_DETAIL = "app/MaintainList/UPDATE_DETAIL";
export const UPDATE_DETAIL_COMPLETE = "app/MaintainList/UPDATE_DETAIL_COMPLETE";
export const FETCH_ALL_MAINTAIN_SCHEDULE =
  "app/MaintainList/FETCH_ALL_MAINTAIN_SCHEDULE";
export const FETCH_ALL_MAINTAIN_SCHEDULE_COMPLETE =
  "app/MaintainList/FETCH_ALL_MAINTAIN_SCHEDULE_COMPLETE";
export const UPDATE_MAINTAIN_SCHEDULE =
  "app/MaintainList/UPDATE_MAINTAIN_SCHEDULE";
export const UPDATE_MAINTAIN_SCHEDULE_COMPLETE =
  "app/MaintainList/UPDATE_MAINTAIN_SCHEDULE_COMPLETE";
