/*
 *
 * NotificationCategory constants
 *
 */

export const DEFAULT_ACTION = "app/NotificationCategory/DEFAULT_ACTION";

export const CREATE_NOTIFICATION_CATEGORY_ACTION = "app/NotificationCategory/CREATE_NOTIFICATION_CATEGORY_ACTION";
export const CREATE_NOTIFICATION_CATEGORY_COMPLETE_ACTION = "app/NotificationCategory/CREATE_NOTIFICATION_CATEGORY_COMPLETE_ACTION";

export const FETCH_NOTIFICATION_CATEGORY_ACTION = "app/NotificationCategory/FETCH_NOTIFICATION_CATEGORY_ACTION";
export const FETCH_NOTIFICATION_CATEGORY_COMPLETE = "app/NotificationCategory/FETCH_NOTIFICATION_CATEGORY_COMPLETE";

export const UPDATE_NOTIFICATION_CATEGORY_ACTION = "app/NotificationCategory/UPDATE_NOTIFICATION_CATEGORY_ACTION";
export const UPDATE_NOTIFICATION_CATEGORY_COMPLETE = "app/NotificationCategory/UPDATE_NOTIFICATION_CATEGORY_COMPLETE";

export const DELETE_NOTIFICATION_CATEGORY_ACTION = "app/NotificationCategory/DELETE_NOTIFICATION_CATEGORY_ACTION";
export const DELETE_NOTIFICATION_CATEGORY_COMPLETE = "app/NotificationCategory/DELETE_NOTIFICATION_CATEGORY_COMPLETE";
