/*
 *
 * Config Receive constants
 *
 */

export const DEFAULT_ACTION = 'app/Receives/DEFAULT_ACTION';

export const FETCH_ALL_NOTIFY_RECEIVE_CONFIG = 'app/Receives/FETCH_ALL_NOTIFY_RECEIVE_CONFIG';
export const FETCH_ALL_NOTIFY_RECEIVE_CONFIG_COMPLETE = 'app/Receives/FETCH_ALL_NOTIFY_RECEIVE_CONFIG_COMPLETE';

export const UPDATE_NOTIFY_RECEIVE_CONFIG = 'app/Receives/UPDATE_NOTIFY_RECEIVE_CONFIG';
export const UPDATE_NOTIFY_RECEIVE_CONFIG_COMPLETE = 'app/Receives/UPDATE_NOTIFY_RECEIVE_CONFIG_COMPLETE';

export const UPDATE_ALL_NOTIFY_RECEIVE_CONFIG = 'app/Receives/UPDATE_ALL_NOTIFY_RECEIVE_CONFIG';
export const UPDATE_ALL_NOTIFY_RECEIVE_CONFIG_COMPLETE = 'app/Receives/UPDATE_ALL_NOTIFY_RECEIVE_CONFIG_COMPLETE';


