/*
 *
 * NotificationFee constants
 *
 */

export const DEFAULT_ACTION = "app/NotificationFee/DEFAULT_ACTION";

export const FETCH_APARTMENT_FEE_REMINDER =
  "app/NotificationFee/FETCH_APARTMENT_FEE_REMINDER";
export const FETCH_APARTMENT_FEE_REMINDER_COMPLETE =
  "app/NotificationFee/FETCH_APARTMENT_FEE_REMINDER_COMPLETE";

export const FETCH_ALL_ANNOUNCEMENT_TEMPLATE_FEE =
  "app/NotificationFee/FETCH_ALL_ANNOUNCEMENT_TEMPLATE_FEE";
export const FETCH_ALL_ANNOUNCEMENT_TEMPLATE_FEE_COMPLETE =
  "app/NotificationFee/FETCH_ALL_ANNOUNCEMENT_TEMPLATE_FEE_COMPLETE";

export const FETCH_ANNOUNCEMENT_TEMPLATE_FEE =
  "app/NotificationFee/FETCH_ANNOUNCEMENT_TEMPLATE_FEE";
export const FETCH_ANNOUNCEMENT_TEMPLATE_FEE_COMPLETE =
  "app/NotificationFee/FETCH_ANNOUNCEMENT_TEMPLATE_FEE_COMPLETE";

export const CREATE_NOTIFICATION_FEE_REMINDER =
  "app/NotificationFee/CREATE_NOTIFICATION_FEE_REMINDER";
export const CREATE_NOTIFICATION_FEE_REMINDER_COMPLETE =
  "app/NotificationFee/CREATE_NOTIFICATION_FEE_REMINDER_COMPLETE";

export const FETCH_CATEGORY = "app/NotificationFee/FETCH_CATEGORY";
export const FETCH_CATEGORY_COMPLETE =
  "app/NotificationFee/FETCH_CATEGORY_COMPLETE";

export const FETCH_NOTIFICATION_TO_PRINT =
  "app/NotificationFee/FETCH_NOTIFICATION_TO_PRINT";
export const FETCH_NOTIFICATION_TO_PRINT_COMPLETE =
  "app/NotificationFee/FETCH_NOTIFICATION_TO_PRINT_COMPLETE";

export const SHOW_CHOOSE_TEMPLATE_LIST =
  "app/NotificationFee/SHOW_CHOOSE_TEMPLATE_LIST";

export const FETCH_APARTMENT_SENT = "app/NotificationFee/FETCH_APARTMENT_SENT";
export const FETCH_APARTMENT_SENT_COMPLETE =
  "app/NotificationFee/FETCH_APARTMENT_SENT_COMPLETE";

export const FETCH_BUILDING_AREA_ACTION =
  "app/NotificationFee/FETCH_BUILDING_AREA_ACTION";
export const FETCH_BUILDING_AREA_COMPLETE_ACTION =
  "app/NotificationFee/FETCH_BUILDING_AREA_COMPLETE_ACTION";
